### ISSUE TITLE
[NetCore/Linux/Microsoft.Data.SqlClient] SQLite Error: 'index UC_Version already exists'.

### ISSUE THREAD

**Issue by VirusFree** [fluentmigrator/fluentmigrator#1039]
1. I am testing with the sample from https://fluentmigrator.github.io/articles/quickstart.html
(i will attach the code but it's basically just the sample with no modifications)
[FluentMigratorTest.zip](https://github.com/fluentmigrator/fluentmigrator/files/3355939/FluentMigratorTest.zip)
2. Using netcoreapp 2.2
3. In windows it runs fine but,
4. in ubuntu ( with published self-contained targeting linux-64)
Runs ok the first time and every time after that i get :
-----------------------------------------------------
VersionUniqueMigration migrating
-----------------------------------------------------
Beginning Transaction
CreateIndex VersionInfo (Version)
!!! SQLite Error 1: 'index UC_Version already exists'.
While Processing:
"CREATE UNIQUE INDEX "UC_Version" ON "VersionInfo" ("Version" ASC)"
!!! +- SQLite Error 1: 'index UC_Version already exists'.
Rolling back transaction

Unhandled Exception: System.Exception: SQLite Error 1: 'index UC_Version already exists'.
While Processing:
"CREATE UNIQUE INDEX "UC_Version" ON "VersionInfo" ("Version" ASC)" ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 1: 'index UC_Version already exists'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)
   --- End of inner exception stack trace ---
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)
   at FluentMigrator.Runner.StopWatch.Time(Action action)
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)
   at FluentMigrator.Runner.MigrationRunner.ApplyMigrationUp(IMigrationInfo migrationInfo, Boolean useTransaction)
   at FluentMigrator.Runner.VersionLoader.LoadVersionInfo()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at FluentMigrator.Runner.MigrationRunner.IsMigrationStepNeededForUpMigration(IMigrationInfo migration, Int64 targetVersion)
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass59_0.<GetUpMigrationsToApply>b__0(KeyValuePair`2 pair)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Int64 targetVersion, Boolean useAutomaticTransactionManagement)
   at FluentMigratorTest.Program.Main(String[] args)
Aborted (core dumped)

**Comment by warappa** [comment]
This issue is not only for SQL Server or SQLite, also for Postgres. So I think we can definitely say its provider-agnostic.

The workaround:
**Don't** set `CreateWithPrimaryKey` to `true` - **set it to `false`**.

Background:
I'm running a Postgres integration test with an **empty(!) database with only 1 migration**. The workaround is the difference between the beforementioned exception and a working integration test.

Broken:
```csharp
[VersionTableMetaData]
public class PostgresVersionTable : IVersionTableMetaData
{
    public string SchemaName => "public";

    public string TableName => "versioninfo";

    public string ColumnName => "version";

    public string AppliedOnColumnName => "appliedon";

    public string DescriptionColumnName => "description";

    public bool OwnsSchema => true;

    public string UniqueIndexName => "uc_version";

    public bool CreateWithPrimaryKey => true; // the issue is here
}
```

Working:
```csharp
[VersionTableMetaData]
public class PostgresVersionTable : IVersionTableMetaData
{
    public string SchemaName => "public";

    public string TableName => "versioninfo";

    public string ColumnName => "version";

    public string AppliedOnColumnName => "appliedon";

    public string DescriptionColumnName => "description";

    public bool OwnsSchema => true;

    public string UniqueIndexName => "uc_version";

    public bool CreateWithPrimaryKey => false; // fixed
}
```

### Info
FluentMigrator: 8.0.1
.NET: 10
Database: Postgres (Npgsql@9.0.3)

**Comment by jzabroski** [comment]
> This issue is not only for SQL Server or SQLite, also for Postgres. So I think we can definitely say its provider-agnostic.
> 
> The workaround: **Don't** set `CreateWithPrimaryKey` to `true` - **set it to `false`**.

Thanks @warappa - very helpful information/context. I added this to the 9.0 milestone.
