### ISSUE TITLE
Identity column with seed in Oracle

### ISSUE THREAD

**Issue by ryabikin** [fluentmigrator/fluentmigrator#1040]
I'm getting "Specified cast is not valid."  when trying to use
`FluentMigrator.Oracle.OracleExtensions.Identity(syntax, FluentMigrator.OracleGenerationType.ByDefault, 1, 1)`

This works fine:
`FluentMigrator.Oracle.OracleExtensions.Identity(syntax, FluentMigrator.OracleGenerationType.ByDefault)`

Exception details:
`System.InvalidCastException: Specified cast is not valid.
   at FluentMigrator.Infrastructure.Extensions.AdditionalFeaturesExtensions.GetAdditionalFeature[T](ISupportAdditionalFeatures additionalFeatures, String key, T defaultValue)
   at FluentMigrator.Runner.Generators.Oracle.Oracle12CColumn.GetIdentityString(ColumnDefinition column)
   at FluentMigrator.Runner.Generators.Oracle.Oracle12CColumn.FormatIdentity(ColumnDefinition column)
   at FluentMigrator.Runner.Generators.Base.ColumnBase.Generate(ColumnDefinition column)
   at FluentMigrator.Runner.Generators.Generic.GenericGenerator.Generate(CreateColumnExpression expression)
   at FluentMigrator.Runner.Generators.Oracle.OracleGenerator.Generate(CreateColumnExpression expression)
   at FluentMigrator.Runner.Processors.ProcessorBase.Process(CreateColumnExpression expression)
   at FluentMigrator.Expressions.CreateColumnExpression.ExecuteWith(IMigrationProcessor processor)
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass79_0.<ExecuteExpressions>b__1()
   at FluentMigrator.Runner.StopWatch.Time(Action action)
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)`

Please advise how to get it working.

**Comment by jzabroski** [comment]
Can you put together a full repro and push it to GitHub? Thanks.

**Comment by fubar-coder** [comment]
@jzabroski It looks like a cast error.

`startsWith` is either a `long` or an `int`, while `incrementBy` is always an `int` (instead of the requested `long`).

The problems should be fixed by making the following changes:

* Changing `object` to `long` in [OracleExtensions, line 120](https://github.com/fluentmigrator/fluentmigrator/blob/628fffa6947d8cd966bbbf20de981546e12dfa41/src/FluentMigrator.Extensions.Oracle/Oracle/OracleExtensions.cs#L120)
* Changing `long?` to `int?` in [Oracle12CColumn, line 61](https://github.com/fluentmigrator/fluentmigrator/blob/77cce9d0d932fc199ab1e8275d1500b73ef2429a/src/FluentMigrator.Runner.Oracle/Generators/Oracle/Oracle12CColumn.cs#L61).

**Comment by ryabikin** [comment]
Thanks for looking into the issue. Do you still need sample code for reproducing it?

**Comment by jzabroski** [comment]
@ryabikin No repro needed.  If you want to submit a PR, i will review and merge..  Should be straight forward.

**Comment by BigYellowHammer** [comment]
I believe this bug can be closed

**Comment by jzabroski** [comment]
Thanks for catching that.
