### ISSUE TITLE
Using FluentMigrator along with Azure Functions

### ISSUE THREAD

**Issue by cfgj** [fluentmigrator/fluentmigrator#1079]
Hi,
I've been trying to use azure function v2 along with fluent migrator v3.2.1 but so far without success. As you can see, I've registered and configured fluent migrator and when I want to resolve migration runner type argument null exception with message "Value cannot be null.\r\nParameter name: assembly" is thrown.

```
   at FluentMigrator.Infrastructure.SingleAssembly..ctor(Assembly assembly)
   at lambda_method(Closure )
   at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7840
   at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7825
   at lambda_method(Closure )
   at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7840
   at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7825
   at lambda_method(Closure , IResolverContext )
   at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 224
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 195
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.ScopedServiceProvider.GetService(Type serviceType) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\ScopedServiceProvider.cs:line 25
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at AzureFunction.DatabaseService.RunMigrations(HttpRequest request) in C:\AzureFunction\Startup.cs:line 46
   at lambda_method(Closure , DatabaseService , Object[] )
   at Microsoft.Azure.WebJobs.Host.Executors.VoidMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidMethodInvoker.cs:line 20
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
```

```csharp
using FluentMigrator;
using FluentMigrator.Runner;
using Microsoft.AspNetCore.Http;
using Microsoft.Azure.Functions.Extensions.DependencyInjection;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Extensions.DependencyInjection;
using System;

[assembly: FunctionsStartup(typeof(AzureFunction.Startup))]
namespace AzureFunction
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            var connStr = "...";
            builder.Services
                .AddLogging(loggingBuilder => loggingBuilder.AddFluentMigratorConsole())
                .AddFluentMigratorCore()
                .ConfigureRunner(runnerBuilder => runnerBuilder
                    .AddSqlServer()
                    .WithGlobalConnectionString(connStr)
                    .ScanIn(GetType().Assembly).For.Migrations()
                );
        }
    }

    public class DatabaseService
    {
        private readonly IServiceProvider _servicePrivder;

        public DatabaseService(IServiceProvider serviceProvider)
        {
            _servicePrivder = serviceProvider;
        }

        [FunctionName("run-migrations")]
        public void RunMigrations(
            [HttpTrigger(AuthorizationLevel.Anonymous, "put", Route = "db/migrations/run")] HttpRequest request)
        {
            using (var scope = _servicePrivder.CreateScope())
            {
                var runner = scope.ServiceProvider.GetRequiredService<IMigrationRunner>();
                runner.MigrateUp();
            }
        }
    }

    [Migration(1)]
    public class InitDB : Migration
    {
        public override void Down() { }

        public override void Up() { }
    }
}
```

Can you give me a hint what am I doing wrong?

Thank you in advance.

**Comment by jzabroski** [comment]
This is slightly difficult for me to weigh in on, given I have never used Azure Functions, so I'm not even sure where to begin.

I would guess your Startup : FunctionsStartup is incorrectly configured, but I don't see where.

**Comment by jzabroski** [comment]
@cfgj I found this interesting nuget of wisdom from SimpleInjector's architect:

https://github.com/simpleinjector/SimpleInjector/issues/536#issuecomment-382438219

A bit messy, but it appears the Azure Functions guys sort of hamfisted this one.

**Comment by jzabroski** [comment]
It's also possible you are running into #1065

**Comment by jzabroski** [comment]
Do let me know if you find a better way.

I suspect Azure Functions has an integration testing framework, but none of these ASP.NET/Azure integration testing frameworks are very good (IMHO) - I got into a debate with some Softies about it and they werent too happy with my critiques.  There's a Code Camp coming up here in Massachussets, maybe there will be a session on Azure FUnctions I can go watch to see if its as painful as it looks.

**Comment by kristianschneider** [comment]
Hi @cfgj 

I seem to have ended up with the same issue as you and have reached a dead-end.
What solution did you end up with ?

**Comment by jzabroski** [comment]
@kristianschneider Did the solution in https://github.com/simpleinjector/SimpleInjector/issues/536#issuecomment-382438219 not work for you?  I mentioned it above.
