### ISSUE TITLE
DefaultEmbeddedResourceProvider Error

### ISSUE THREAD

**Issue by chrisheil** [fluentmigrator/fluentmigrator#1135]
I recently upgraded to version 3.2.1 and tried running a migration with an EmbeddedScript. I am now getting the following error

```
Unhandled Exception: System.InvalidOperationException: Unable to activate type 'FluentMigrator.Infrastructure.DefaultEmbeddedResourceProvider'. The following constructors are ambiguous:
Void .ctor(System.Collections.Generic.IEnumerable`1[System.Reflection.Assembly])
Void .ctor(FluentMigrator.Infrastructure.IAssemblyCollection)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateEnumerable(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
```

My Program.cs file looks like this

```
class Program
{
    static void Main(string[] args)
    {
        var builder = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json");
        IConfiguration config = new ConfigurationBuilder()
        .AddJsonFile("appsettings.json", true, true)
        .Build();
        var announcer = new ConsoleAnnouncer();

        // Processor specific options (usually none are needed)
        var options = new ProcessorOptions();

        var processorFactory = new SqlServerProcessorFactory();

        // Initialize the processor
        using (var processor = processorFactory.Create(
            config["ConnectionStrings"],
            announcer,
            options))
        {
            // Configure the runner
            var context = new RunnerContext(announcer)
            {
                ApplicationContext = config["ApplicationContext"]
            };

            // Create the migration runner
            var runner = new MigrationRunner(
                // Specify the assembly with the migrations
                typeof(MyMigrationProject).Assembly,
                context,
                processor);

            // Run the migrations
            runner.MigrateUp();
        }
    }
}
```

**Comment by jzabroski** [comment]
Can you provide me some more information?  What previous version of the framework and what previous version of FluentMigrator?  Also, is this really the full stack trace?

That said, it looks like you're not using the Microsoft DI framework.  Can you look at the new Example project in the head of master and ask any questions.

Thanks.

**Comment by chrisheil** [comment]
The original package was FluentMigrator v1.6.2, and the csproj was 4.5.1 (also worked with 4.7 before updating to core)

I realize this code is obsolete now, and I am attempting to try the latest setup now, but I did find at least [one other person](https://stackoverflow.com/questions/53091898/unable-to-activate-type-fluentmigrator-infrastructure-defaultembeddedresourcepr) facing this issue so figured I would open a ticket.

We are using TinyIoC, I'll take a look into that as a possible source of issue. Best case scenario it is something that can be fixed in that!

I had trimmed out some of the stack trace since it had some project names in it and I'm just overly cautious about that sort of stuff. Here is a full (scrubbed) version of the stack trace

```
Unable to activate type 'FluentMigrator.Infrastructure.DefaultEmbeddedResourceProvider'. The following constructors are ambiguous:
Void .ctor(System.Collections.Generic.IEnumerable`1[System.Reflection.Assembly])
Void .ctor(FluentMigrator.Infrastructure.IAssemblyCollection)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateEnumerable(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at FluentMigrator.Builders.Execute.ExecuteExpressionRoot.EmbeddedScript(String embeddedSqlScriptName)
   at MyProject.Migrations.Initial.InitialSchemaCreation.Up() in C:\MyProject\Migrations\Initial\InitialSchemaCreation.cs:line 16 <======== This is where the Execute.EmbeddedScript line is
   at FluentMigrator.MigrationBase.GetUpExpressions(IMigrationContext context)
   at FluentMigrator.Runner.MigrationRunner.<>c.<ApplyMigrationUp>b__68_0(IMigration m, IMigrationContext c)
   at FluentMigrator.Runner.MigrationRunner.ExecuteMigration(IMigration migration, Action`2 getExpressions)
   at FluentMigrator.Runner.MigrationRunner.ApplyMigrationUp(IMigrationInfo migrationInfo, Boolean useTransaction)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Int64 targetVersion, Boolean useAutomaticTransactionManagement)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Boolean useAutomaticTransactionManagement)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp()
   at UFT.DatabaseMigrations.Runner.Program.LegacyMigrator() in C:\MyProject\UFT.DatabaseMigrations.Runner\Program.cs:line 94
   at UFT.DatabaseMigrations.Runner.Program.Main(String[] args) in C:\MyProject\UFT.DatabaseMigrations.Runner\Program.cs:line 22
```

**Comment by chrisheil** [comment]
@jzabroski I have created a new test project with just a simple migration in it to eliminate varibales

https://github.com/chrisheil/FMTroubleshooting

When I try to run this I get the same error.

**Comment by fubar-coder** [comment]
This does indeed seem like a bug where I created a simple service provider in an obsolete [`MigrationContext` constructor](https://github.com/fluentmigrator/fluentmigrator/blob/e82aafa20e6dbe3cefa221303fe23cf8bf59fffd/src/FluentMigrator/Infrastructure/MigrationContext.cs#L55).

**Comment by jzabroski** [comment]
And,looking, @fubar-coder ,  why are you calling `ValidateScopes: false`? :)

**Comment by fubar-coder** [comment]
I didn't want to open a scope that I had to manage too. There is just one scope - the root one, which should be enough for supporting an obsolete use case 😛 .

**Comment by chrisheil** [comment]
For what its worth, I seem to have resolved this issue by simply upgrading to the recommended implementation. The only thing I am confused about is where ApplicationContext went, but I found a workaround for now.

If you want I can close the issue, or keep it open. I could see this being a reason to remove the obsolete code altogether in the next version, since no one else reported it as an issue in over a year, or maybe the fix is relatively easy and you want to keep this open until it is resolved.

Either way, thanks for the help and keep up the great work!

**Comment by jzabroski** [comment]
Yeah, the workaround for applicationcontext is just to inject an object you want / use service locator (the simplest service locator being to use Microsoft ConfigurationManager in .NET Core- but remember, it's all a giant flattened key-value pair dictionary in the end).  Doesn't work for dotnet-fm users, but for In Process Runner users, it works fine.

**Comment by jzabroski** [comment]
> I realize this code is obsolete now, and I am attempting to try the latest setup now, but I did find at least [one other person](https://stackoverflow.com/questions/53091898/unable-to-activate-type-fluentmigrator-infrastructure-defaultembeddedresourcepr) facing this issue so figured I would open a ticket.

Thanks for that link.  I realized I somehow stopped watching fluent-migrator tag on StackOverflow (by accident).  We could have caught this sooner, but I dont think that StackOverflow user reported it here.  Glad you got through this.
