### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly.

### ISSUE THREAD

**Issue by ZoranMaricic** [fluentmigrator/fluentmigrator#1188]
I am always getting this error : 
`System.IO.FileNotFoundException: Could not load file or assembly. The system cannot find the file specified.` 
when i put Insert.IntoTable().Row(new anonymous type).

**Comment by jzabroski** [comment]
@ZoranMaricic  Need full stack trace - it should say which assembly could not be loaded. Thanks.

**Comment by ZoranMaricic** [comment]
Unhandled Exception:
 
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at FluentMigrator.Runner.Initialization.AssemblySourceMigrationRunnerConventionsAccessor.<>c__DisplayClass1_0.<.ctor>b__0() in 
/home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner.Core/Initialization/AssemblySourceMigrationRunnerConventionsAccessor.cs:line 50
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.FluentMigratorServiceCollectionExtensions.<>c.<AddFluentMigratorCore>b__0_2(IServiceProvider sp) in 
/home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner/FluentMigratorServiceCollectionExtensions.cs:line 91
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at FluentMigrator.Runner.Initialization.TaskExecutor.RunnerScope..ctor(TaskExecutor executor) in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner/Initialization/TaskExecutor.cs:line 253
   at FluentMigrator.Runner.Initialization.TaskExecutor.Execute() in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner/Initialization/TaskExecutor.cs:line 157
   at FluentMigrator.DotNet.Cli.Commands.BaseCommand.ExecuteMigrations(MigratorOptions options, IConsole console) in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.DotNet.Cli/Commands/BaseCommand
.cs:line 32
   at FluentMigrator.DotNet.Cli.Commands.Migrate.OnExecute(IConsole console) in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.DotNet.Cli/Commands/Migrate.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass142_0.<OnExecute>b__0()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](IConsole console, String[] args)
   at FluentMigrator.DotNet.Cli.Program.Main(String[] args) in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.DotNet.Cli/Program.cs:line 35

**Comment by jzabroski** [comment]
I think your Migrations assembly might be compiled against a different target framework than FluentMigrator.DotNet.Cli - V4 of this tool supports multiple frameworks and we plan to patch V3 to support multiple as well, but we were stuck wrapping our head around best practices here in absence of Microsoft providing clear guidance.  See: #1139 , #1072  and #1016  for background if you're interested.

**Comment by jzabroski** [comment]
@ZoranMaricic  I'm assuming thumbs up means you agree- closing issue.  Please re-open with more details if I'm mistaken.  THanks!
