### ISSUE TITLE
The error was Autorisation CREATE TABLE every time restart application

### ISSUE THREAD

**Issue by mathdev92** [fluentmigrator/fluentmigrator#1227]
Hello,

I have a rights error if my user is not db_owner. He tries to create the table every time. I give the rights, I launch my application: OK, I withdraw the rights, I restart: Error.
Why is he trying to create this table every time when there is data in it.

i'm in dotnet core 3.1 with SQL Server 13

Thanks

Application startup exception: System.Exception: An error occured executing the following sql:
CREATE TABLE [dbo].[VersionInfo] ([Version] BIGINT NOT NULL)
The error was Autorisation CREATE TABLE refusée dans la base de données 'REC_OFFICE'.

 ---> System.Data.SqlClient.SqlException (0x80131904): Autorisation CREATE TABLE refusée dans la base de données 'REC_OFFICE'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at FluentMigrator.Runner.Processors.SqlServer.SqlServerProcessor.ExecuteNonQuery(String sql)
ClientConnectionId:e7ff1710-df49-4dfa-ac2d-835ddd418528
Error Number:262,State:1,Class:14
   --- End of inner exception stack trace ---
   at FluentMigrator.Runner.Processors.SqlServer.SqlServerProcessor.ExecuteNonQuery(String sql)
   at FluentMigrator.Runner.Processors.SqlServer.SqlServerProcessor.Process(String sql)
   at FluentMigrator.Runner.Processors.ProcessorBase.Process(CreateTableExpression expression)
   at FluentMigrator.Expressions.CreateTableExpression.ExecuteWith(IMigrationProcessor processor)
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass79_0.<ExecuteExpressions>b__1()
   at FluentMigrator.Runner.StopWatch.Time(Action action)
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)
   at FluentMigrator.Runner.MigrationRunner.ExecuteMigration(IMigration migration, Action`2 getExpressions)
   at FluentMigrator.Runner.MigrationRunner.ApplyMigrationUp(IMigrationInfo migrationInfo, Boolean useTransaction)
   at FluentMigrator.Runner.MigrationRunner.Up(IMigration migration)
   at FluentMigrator.Runner.VersionLoader.LoadVersionInfo()
   at FluentMigrator.Runner.VersionLoader..ctor(IProcessorAccessor processorAccessor, IConventionSet conventionSet, IMigrationRunnerConventions conventions, IVersionTableMetaData versionTableMetaData, IMigrationRunner runner)

**Comment by jzabroski** [comment]
@mathdev92 This isn't a FluentMigrator issue per say, but a question for your DBA team to help you with.  That said:

#### Best Practices
1. Run FluentMigrator as an `sa`-account or as `db_owner`.
    1. If you don't do this, you run the risk of very pernicious issues related to schema-scoped objects. In particular, if you have a view that doesn't use schema-qualified table names, then the T-SQL interpreter will fail to resolve those objects, and the migration will fail.
    2. Frankly, it's not a bad feature idea to have FluentMigrator have a `--verify-permissions` flag on the runner to ensure people don't start the runner with inadequate permissions.  If you want to help, please research various database's permissions required to execute DDL statements and provide corresponding documentation URLs.
    3. *War story:* Earlier in my career, I ran into a customer in the staffing industry who was unbearably rude.  We deployed our database changes to a customer's on-site SQL Server DBMS, and between user acceptance testing and go-live, he changed the account's permissions without telling us, and completely wrecked the release and blamed us for the problem.  I'll never forget his exact words: "I'll send my dog's farts to your house," whatever that means.  It's true: Everything is bigger in Texas, even the characters.
2. Always schema-qualify your objects, and their referenced objects.
    1. It might be a valid use case to partition your FluentMigrator migrations so that each Runner only has permission to execute migrations in a specific schema, rather than entire database.  In that case, you'll want the runner user to have authorization on the schema, as opposed to being db_owner.  It would also be useful in SQL Server to `GRANT VIEW SERVER STATE` as well, but not entirely necessary.  If this is truly how you want to do things, you might also want a team discussion with your DBAs about how to handle things like `SCHEMA TRANSFER` tricks used by DBAs for loading large datasets/updating partitions.  
3. Make sure your permissions for the Runner user accounts are consistent across all servers.
    1. Put one person in charge, document their responsibilities before each major release, and/or automate the verification process.  Whatever you do, drill it in everyone's head that it's not cool to mess with these account permissions.
