### ISSUE TITLE
AddJet with other database throws exception System.ArgumentException

### ISSUE THREAD

**Issue by lszczygielek** [fluentmigrator/fluentmigrator#1233]
I'm working on In-Process runner using .NET Framework 4.6.2. I found an issue that when I add Jet support and SqlServer and call operations on SqlServer then migrations are applied, but exception is present on disposing service scope. I have an example code:

```
class Program
{
    static void Main(string[] args)
    {
        var serviceProvider = CreateServices();

        using (var scope = serviceProvider.CreateScope())
        {
            UpdateDatabase(scope.ServiceProvider);
        } // here is an exception when SqlServer is in use

        Console.WriteLine("Press any key to exit...");
        Console.ReadKey();
    }

    private static IServiceProvider CreateServices()
    {
        var connectionString = @"Server=SERVER\INSTANCE;Database=DATABASE;User Id=USER;Password=PASSWORD;";

        return new ServiceCollection()
            .AddLogging(lb =>
            {
                lb.SetMinimumLevel(LogLevel.Debug)
                    .AddFluentMigratorConsole();
                lb.Services.Configure<FluentMigratorLoggerOptions>(o => o.ShowSql = true);
            })
            .AddFluentMigratorCore()
            .ConfigureRunner(rb => rb
                .AddJet()
                .AddSqlServer()
                .ScanIn(typeof(Program).Assembly).For.All())
            .Configure<ProcessorOptions>(o => o.ConnectionString = connectionString) // SqlServer connection string
            .Configure<SelectingProcessorAccessorOptions>(cfg => cfg.ProcessorId = "sqlserver") // Lets operate on Sql Server
            .BuildServiceProvider(false);
    }

    private static void UpdateDatabase(IServiceProvider serviceProvider)
    {
        var runner = serviceProvider.GetRequiredService<IMigrationRunner>();
        runner.MigrateUp();
    }
}

[Migration(1)]
public class FakeMigration : Migration
{
    public override void Up()
    {
    }

    public override void Down()
    {
    }
}

```

```
Exception:

System.ArgumentException
  HResult=0x80070057
  Message=An OLE DB Provider was not specified in the ConnectionString.  An example would be, 'Provider=SQLOLEDB;'.
  Source=System.Data
  StackTrace:
   at System.Data.OleDb.OleDbConnectionString.ValidateProvider(String progid)
   at System.Data.OleDb.OleDbConnectionString.ValidateConnectionString(String connectionString)
   at System.Data.OleDb.OleDbConnectionString..ctor(String connectionString, Boolean validate)
   at System.Data.OleDb.OleDbConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at System.Data.OleDb.OleDbConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.OleDb.OleDbConnection.set_ConnectionString(String value)
   at FluentMigrator.Runner.Processors.Jet.JetProcessor.<>c__DisplayClass8_0.<.ctor>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at FluentMigrator.Runner.Processors.Jet.JetProcessor.EnsureConnectionIsClosed()
   at FluentMigrator.Runner.Processors.Jet.JetProcessor.Dispose(Boolean isDisposing)
   at FluentMigrator.Runner.Processors.ProcessorBase.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceScope.Dispose()
   at XXX.Program.Main(String[] args) in XXX\Program.cs:line 30

  This exception was originally thrown at this call stack:
	System.Data.OleDb.OleDbConnectionString.ValidateProvider(string)
	System.Data.OleDb.OleDbConnectionString.ValidateConnectionString(string)
	System.Data.OleDb.OleDbConnectionString.OleDbConnectionString(string, bool)
	System.Data.OleDb.OleDbConnectionFactory.CreateConnectionOptions(string, System.Data.Common.DbConnectionOptions)
	System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(System.Data.Common.DbConnectionPoolKey, System.Data.ProviderBase.DbConnectionPoolGroupOptions, ref System.Data.Common.DbConnectionOptions)
	System.Data.OleDb.OleDbConnection.ConnectionString_Set(System.Data.Common.DbConnectionPoolKey)
	System.Data.OleDb.OleDbConnection.ConnectionString.set(string)
	FluentMigrator.Runner.Processors.Jet.JetProcessor..ctor.AnonymousMethod__0()
	System.Lazy<T>.CreateValue()
	System.Lazy<T>.LazyInitValue()
    ...
    [Call Stack Truncated]

```

**Comment by jzabroski** [comment]
@lszczygielek Which version of FluentMigrator?  Thanks for the detailed repro!

**Comment by lszczygielek** [comment]
I'm using FluentMigrator 3.2.6 with .NET Framework 4.6.2.
