### ISSUE TITLE
if_exists works in reverted way on oracle

### ISSUE THREAD

**Issue by fairking** [fluentmigrator/fluentmigrator#1263]
**Describe the bug**
The check {if index exists} working in reverted way.

**To Reproduce**
The following statement:
```
if (Schema.Table("core_users").Index("ix_core_users_discriminator").Exists())
      Delete.Index("ix_core_users_discriminator").OnTable("core_users").OnColumn("discriminator");
```
throws an error: `ORA-01418: specified index does not exist`
Sql: `DROP INDEX ix_core_users_discriminator`

**Expected behavior**
It should not attempt to delete the index

**Information (please complete the following information):**
 - OS: Windows 10
 - Platform .NET Core 3.1.x
 - FluentMigrator version 3.2.6
 - FluentMigrator runner
 - Database Management System: Oracle
 - Database Management System Version: "Oracle 18xe"

**Additional context**
If I revert the statement to:
```
if (!Schema.Table("core_users").Index("ix_core_users_discriminator").Exists())
      Delete.Index("ix_core_users_discriminator").OnTable("core_users").OnColumn("discriminator");
```
See the "!". It works with no issue.

**Comment by jzabroski** [comment]
So is this basically your migration?
```C#
public class M1_DropIndex : Migration
{
  public void Up()
  {
    Create.Index("ix_core_users_discriminator").OnTable("core_users").OnColumn("discriminator");
  }
  public void Down()
  {
    if (Schema.Table("core_users").Index("ix_core_users_discriminator").Exists())
      Delete.Index("ix_core_users_discriminator").OnTable("core_users").OnColumn("discriminator");
  }
}
```

If so, the full existence check SQL [should be logged](https://github.com/fluentmigrator/fluentmigrator/blob/c753ddd71c7de565bacf04eeaa03d94ba64646b6/src/FluentMigrator.Runner.Oracle/Processors/Oracle/OracleProcessorBase.cs#L221) before the drop statement.  Can you please copy-paste it?

**Comment by fairking** [comment]
The actual script is very big and it is Uu. The Down is empty. It is like this:
```
public class M1_CreateIndex : Migration
{
  public void Up()
  {
    Create.Index("ix_core_users_discriminator").OnTable("core_users").OnColumn("discriminator");
  }
  public void Down()
  {
  }
}

public class M2_DropIndex : Migration
{
  public void Up()
  {
    if (Schema.Table("core_users").Index("ix_core_users_discriminator").Exists())
          Delete.Index("ix_core_users_discriminator").OnTable("core_users").OnColumn("discriminator");
  }
  public void Down()
  {
  }
}
```

**Comment by jzabroski** [comment]
Can you copy-paste what the output is to the console before the drop statement?  It should log the existence check.  It is a line that look something containing `SELECT 1 FROM ALL_INDEXES WHERE upper(OWNER) = 'core_users' AND upper(INDEX_NAME) = 'ix_core_users_discriminator'`

**Comment by jzabroski** [comment]
Can you also try specifying the schema?

```c#
    public class M1_DropIndex : ForwardOnlyMigration
    {
        public override void Up()
        {
            if (Schema.Schema("mySchemaName").Table("core_users").Index("ix_core_users_discriminator").Exists())
                Delete.Index("ix_core_users_discriminator").OnTable("core_users").OnColumn("discriminator");
        }
    }
```

**Comment by fairking** [comment]
This is how it looks:
```
public override void Up()
{
    ...............
    // Delete [name] and [job_title] columns in [core_users]
    Delete.Column("name").FromTable("core_users");
    Delete.Column("job_title").FromTable("core_users");

    // Delete [discriminator] column in [core_users]
    if (Schema.Table("core_users").Index("ix_core_users_discriminator").Exists())
            Delete.Index("ix_core_users_discriminator").OnTable("core_users").OnColumn("discriminator");
    Delete.Column("discriminator").FromTable("core_users");
    ............
}
```
Terminal:
```
info: FluentMigrator.Runner.MigrationRunner[1004]
      DeleteColumn core_users job_title
DeleteColumn core_users job_title
info: FluentMigrator.Runner.Processors.Oracle.OracleManagedProcessor[1003]
      ALTER TABLE core_users DROP COLUMN job_title
info: FluentMigrator.Runner.MigrationRunner[1002]
      => 0.0209586s
info: FluentMigrator.Runner.MigrationRunner[1004]
      DeleteIndex core_users (discriminator)
DeleteIndex core_users (discriminator)
info: FluentMigrator.Runner.Processors.Oracle.OracleManagedProcessor[1003]
      DROP INDEX ix_core_users_discriminator
fail: FluentMigrator.Runner.MigrationRunner[0]
      ORA-01418: specified index does not exist
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-01418: specified index does not exist
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at FluentMigrator.Runner.Processors.Oracle.OracleProcessorBase.Process(String sql)
   at FluentMigrator.Runner.Processors.ProcessorBase.Process(DeleteIndexExpression expression)
   at FluentMigrator.Expressions.DeleteIndexExpression.ExecuteWith(IMigrationProcessor processor)
   at FluentMigrator.Runner.StopWatch.Time(Action action)
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)
!!! ORA-01418: specified index does not exist
infoRolling back transaction
```

**Comment by fairking** [comment]
If I specify the schema the same error still persists.

**Comment by jzabroski** [comment]
That's strange - also the code for SchemaExists in OracleProcessorBase is strange to me (it's returning an int and implicitly converting it to a bool).  Calling it a day for tonight.

As some pre-bedtime ideas:

An alternative way to write the existence check might be:

```sql
SELECT 
CASE WHEN EXISTS (
  SELECT 1 FROM (
    (
      SELECT CONSTRAINT_NAME
      FROM all_cons_columns
      WHERE table_name = '{0}'
      AND COLUMN_NAME IN = '{1}'
    )
  )
) THEN 1 ELSE 0 END AS PRECONDITION
FROM DUAL
```

**Comment by fairking** [comment]
Tried to run MSSQL Migration and also cannot see any checks on MSSQL:
```
info: FluentMigrator.Runner.MigrationRunner[1004]
      DeleteIndex core_users (discriminator)
DeleteIndex core_users (discriminator)
info: FluentMigrator.Runner.Processors.SqlServer.SqlServer2016Processor[1003]
      DROP INDEX [ix_core_users_discriminator] ON [dbo].[core_users]
info: FluentMigrator.Runner.MigrationRunner[1002]
      => 0.0024254s
```
But because as I remember the index in MSSQL db exists, the result is not ended up with the error about missing index.

So the tests on Oracle and MSSQL show that the check `exists` is not processed by the actual sql query.

**Comment by fairking** [comment]
1. I can see some of the `exists` checks do not log the sql query into the terminal.
2. I am not sure if `exists` check run the query in `ReadCommitted` or `ReadUncommitted`. So eg. I have table renamed in the same script and then I would like to drop the index. Originally that index must to be dropped before rename:
```
Rename.Table("core_user_groups").To("core_staff_groups");
...
// In ReadComitted the table `core_staff_groups` does not exist so the index also does not exist.
if (Schema.Table("core_staff_groups").Index("ix_core_users_discriminator").Exists())
    Delete.Index("ix_core_users_discriminator").OnTable("core_staff_groups").OnColumn("discriminator");
```
3. Regarding the situation I have with the index `ix_core_users_discriminator` that column definitely wasn't renamed so there must be something else than `ReadCommitted` especially that the Oracle does not support transactions on Rename query.
4. Having the query `DROP INDEX ix_core_users_discriminator` in terminal I cannot see it uses the table name. I actually have a situation with this index that in other table I had the same index and I removed it. That's probably why it is not a problem with MSSQL but the problem with Oracle, where the first query removed both indexes for `core_users` and for `core_staff_groups` which have the same name. So the second run throws an exception.
5. Based on the logic from 4 the check must prevent from attemp to remove index on the second table but the truth is all those checks (I found) run and the beginning of the script. And then all other commands.

How it actually looks in my situation:
Code:
```
public override void Up()
{
    Rename.Table("core_user_groups").To("core_staff_groups");
    ...
    if (Schema.Table("core_staff_groups").Index("ix_core_users_discriminator").Exists())
        Delete.Index("ix_core_users_discriminator").OnTable("core_staff_groups").OnColumn("discriminator");
    ...
    if (Schema.Table("core_users").Index("ix_core_users_discriminator").Exists())
        Delete.Index("ix_core_users_discriminator").OnTable("core_users").OnColumn("discriminator"); // Throws error
}
```
Log:
```
info: FluentMigrator.Runner.Processors.Oracle.OracleManagedProcessor[1004]
      Beginning Transaction
Beginning Transaction
info: FluentMigrator.Runner.Processors.Oracle.OracleManagedProcessor[1003]
      SELECT 1 FROM USER_INDEXES WHERE upper(INDEX_NAME) = 'IX_CORE_USERS_DISCRIMINATOR'
info: FluentMigrator.Runner.Processors.Oracle.OracleManagedProcessor[1003]
      SELECT 1 FROM USER_INDEXES WHERE upper(INDEX_NAME) = 'IX_CORE_USERS_DISCRIMINATOR'
RenameTable core_user_groups core_staff_groups
info: FluentMigrator.Runner.MigrationRunner[1004]
      RenameTable core_user_groups core_staff_groups
info: FluentMigrator.Runner.Processors.Oracle.OracleManagedProcessor[1003]
      ALTER TABLE core_user_groups RENAME TO core_staff_groups
info: FluentMigrator.Runner.MigrationRunner[1002]
      => 0.0099369s
DeleteIndex core_staff_groups (discriminator)
info: FluentMigrator.Runner.MigrationRunner[1004]
      DeleteIndex core_staff_groups (discriminator)
info: FluentMigrator.Runner.Processors.Oracle.OracleManagedProcessor[1003]
      DROP INDEX **ix_core_users_discriminator**
info: FluentMigrator.Runner.MigrationRunner[1002]
      => 0.0077028s
info: FluentMigrator.Runner.MigrationRunner[1004]
      DeleteIndex core_users (discriminator)
info: FluentMigrator.Runner.Processors.Oracle.OracleManagedProcessor[1003]
      DROP INDEX **ix_core_users_discriminator**
fail: FluentMigrator.Runner.MigrationRunner[0]
      ORA-01418: specified index does not exist
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-01418: specified index does not exist
```

Hope it helps with understanding the issue and choosing the right behavior to implement in the fluent migrator.

**Comment by jzabroski** [comment]
Thanks.  I probably won't look any further today but I have a checklist of things to investigate.  Ideally I'd like to include a fix (or respond with correct usage syntax) before 3.2.7 is published, which I have a hard cut-off goal of Sunday night for 3.2.7 fixes.

**Comment by fairking** [comment]
Thanks I fixed the script in different way, so no response required. But I I can see now those `exists` checks need to be used carefully assuming they are executed at the beginnig of the script and that the index name must be unique across the scheme (not table like in mssql).

**Comment by jzabroski** [comment]
> But I can see now those `exists` checks need to be used carefully assuming they are executed at the beginnig of the script and that the index name must be unique across the scheme (not table like in mssql).

I did create a batch actions ticket recently to make some of this easier to use: #1221 

Separately, I had a separate idea for allowing monadic-like F#-like computation expressions in FluentMigrator.  See: #987 The idea is that one could use something like LINQ IEnumerable interface and the LINQ syntax to define a monadic-like computation that builds up a list of side effects (aka migrations) and then executes them.  But, in my judgment, there are higher priority features and I don't know if most users would understand or like the idea vs. just fixing bugs and adding more common features like tablespaces/partitions and other things.

**Comment by jzabroski** [comment]
Copy-pasting my comments from #854:

> I believe the reason FluentMigrator uses these out-of-band tests is that most databases require `CREATE TABLE` statements to be the first statement in the transaction. Even so, what I'd like to see in the future is something like:
> 
> ```c#
> If.Schema("foo").Table("Bar").NotExists()
>   .Do((InlineUpMigration d) =>
>     d.Table("Bar").InSchema("foo").Column("a").AsInt64().NotNullable());
> ```
> 
> This would have the portion of FluentMigrator that manages the `System.Data` layer in charge of tracking the "decision tree" for whether a migration should be processed. In theory, I could then unify this with the rather inconsistent `MigrationConstraint` attribute for selectively executing migrations. Neither `IQuerySchema` nor `MigrationConstraint`s support a "live" "decision tree". Both are snapshots at a particular point in time, which I think is rather clunky despite acknowledging the above reasons as to why it was likely coded this way: It's clunky because it limits the usefulness of generating preview migrations, as well as just writing code that works the way you might naturally want to read it working. I think we can do better.

I will try to transfer this comment and the [previous comment above](https://github.com/fluentmigrator/fluentmigrator/issues/1263#issuecomment-639530102) into an architecture decision record to elaborate on what we want to achieve.  I have separately outlined some thoughts on how we can achieve it in #908 : Support an `IUnitOfWork` and  `IUnitOfWorkParticipant` so that migrations "participate" in a larger unit of work and do not know anything about the physical SQL connection, only the logical transaction.  In theory, this proposal would also unlock the ideas I described in #987 for unlocking the full power of `Execute.WithConnection`.

**Comment by jzabroski** [comment]
@fairking I am going to retitle this issue, as I think it is inaccurate based on your last comment here:

> But I can see now those `Exists` checks need to be used carefully assuming they are executed at the beginning of the script and that the index name must be unique across the schema (not table like in SQL Server).

The problem is that Conditionals are not part of the migration itself, so depending on how you run the migration, you may get different results.

One possible workaround (for now) is to effectively patch FluentMigrator.DotNet.Cli migrate parameters to support #1033

**Comment by PhenX** [comment]
I'm thinking about this lately while also thinking about this issue : https://github.com/fluentmigrator/fluentmigrator/issues/854

(Because for now, AFAIK the only thing requiring Up and Down methods to be async are the builder methods to  check if a table, schema, index, etc exist. But I cannot think of another use case than "create table if not exists" or "drop table if exists", or there equivalent for sequences, indexes, etc)

While [@jzabroski's proposal](https://github.com/jzabroski) would make conditionals work the way we want it, it might be hard to implement, and too verbose for 90% of the cases.

While an approach like in [this issue](https://github.com/fluentmigrator/fluentmigrator/issues/1802) (but even simpler) would be a lot easier for most of the DB providers because there syntax allow this. For others, they'll have to be wrapped in a more complex statement, like it would be with this issue.

**Comment by PhenX** [comment]
I asked Claude to tell me everything about the syntax support : 

## Schemas

| DBMS | CREATE IF NOT EXISTS | DROP IF EXISTS | ALTER IF EXISTS | Version Notes | Official Documentation |
|------|:-------------------:|:---------------:|:---------------:|---------------|------------------------|
| **DB2** | ✅ | ❌ | ❌ | CREATE IF NOT EXISTS support | [IBM DB2 CREATE SCHEMA](https://www.ibm.com/docs/en/db2/11.5?topic=statements-create-schema) |
| **Firebird** | ❌ | ❌ | ❌ | No native support | [Firebird Database Structure](https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref30/firebird-30-language-reference.html) |
| **SAP HANA** | ✅ | ✅ | ✅ | Full support in HANA 2.0+ | [SAP HANA CREATE SCHEMA](https://help.sap.com/docs/SAP_HANA_PLATFORM/4fe29514fd584807ac9f2a04f6754767/20d4ecad75191014b3bfe08121f54cd9.html) |
| **Jet (Access)** | N/A | N/A | N/A | No schemas | [Access Database Objects](https://docs.microsoft.com/en-us/office/client-developer/access/desktop-database-reference/database-object-access) |
| **MySQL** | ✅ | ✅ | ❌ | IF NOT EXISTS since MySQL 5.0 | [MySQL CREATE DATABASE](https://dev.mysql.com/doc/refman/8.0/en/create-database.html) |
| **Oracle** | ❌ | ❌ | ❌ | No native support | [Oracle CREATE USER](https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/CREATE-USER.html) |
| **PostgreSQL** | ✅ | ✅ | ❌ | Full support since PostgreSQL 9.1+ | [PostgreSQL CREATE SCHEMA](https://www.postgresql.org/docs/current/sql-createschema.html) |
| **Redshift** | ✅ | ✅ | ❌ | Based on PostgreSQL | [Redshift CREATE SCHEMA](https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_SCHEMA.html) |
| **Snowflake** | ✅ | ✅ | ✅ | Full support | [Snowflake CREATE SCHEMA](https://docs.snowflake.com/en/sql-reference/sql/create-schema) |
| **SQLite** | N/A | N/A | N/A | No schemas | [SQLite Database File Format](https://www.sqlite.org/fileformat.html) |
| **SQL Server** | ❌ | ✅ | ❌ | DROP IF EXISTS since SQL Server 2016 | [SQL Server CREATE SCHEMA](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-schema-transact-sql) |

## Tables

| DBMS | CREATE IF NOT EXISTS | DROP IF EXISTS | ALTER IF EXISTS | Version Notes | Official Documentation |
|------|:-------------------:|:---------------:|:---------------:|---------------|------------------------|
| **DB2** | ✅ | ❌ | ❌ | CREATE IF NOT EXISTS since DB2 9.7 | [IBM DB2 SQL Reference](https://www.ibm.com/docs/en/db2/11.5?topic=statements-create-table) |
| **Firebird** | ❌ | ❌ | ❌ | No native support | [Firebird SQL Reference](https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref30/firebird-30-language-reference.html) |
| **SAP HANA** | ✅ | ✅ | ✅ | Full support in HANA 2.0+ | [SAP HANA SQL Reference](https://help.sap.com/docs/SAP_HANA_PLATFORM/4fe29514fd584807ac9f2a04f6754767/20d58a5f75191014b2fe92141b7df228.html) |
| **Jet (Access)** | ❌ | ❌ | ❌ | No native support | [Microsoft Access SQL Reference](https://docs.microsoft.com/en-us/office/client-developer/access/desktop-database-reference/microsoft-access-sql-reference) |
| **MySQL** | ✅ | ✅ | ❌ | IF NOT EXISTS since MySQL 3.23 | [MySQL CREATE TABLE](https://dev.mysql.com/doc/refman/8.0/en/create-table.html) |
| **Oracle** | ❌ | ❌ | ❌ | No native support | [Oracle SQL Language Reference](https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/CREATE-TABLE.html) |
| **PostgreSQL** | ✅ | ✅ | ✅ | Full support since PostgreSQL 9.1+ | [PostgreSQL CREATE TABLE](https://www.postgresql.org/docs/current/sql-createtable.html) |
| **Redshift** | ✅ | ✅ | ✅ | Based on PostgreSQL | [Amazon Redshift SQL Reference](https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_TABLE_NEW.html) |
| **Snowflake** | ✅ | ✅ | ✅ | Full support | [Snowflake CREATE TABLE](https://docs.snowflake.com/en/sql-reference/sql/create-table) |
| **SQLite** | ✅ | ✅ | ❌ | Support since early versions | [SQLite CREATE TABLE](https://www.sqlite.org/lang_createtable.html) |
| **SQL Server** | ❌ | ✅ | ❌ | DROP IF EXISTS since SQL Server 2016 | [SQL Server CREATE TABLE](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql) |

## Columns

| DBMS | ADD IF NOT EXISTS | DROP IF EXISTS | ALTER IF EXISTS | Version Notes | Official Documentation |
|------|:----------------:|:---------------:|:---------------:|---------------|------------------------|
| **DB2** | ❌ | ❌ | ❌ | Limited support | [IBM DB2 ALTER TABLE](https://www.ibm.com/docs/en/db2/11.5?topic=statements-alter-table) |
| **Firebird** | ❌ | ❌ | ❌ | No native support | [Firebird ALTER TABLE](https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref30/firebird-30-language-reference.html#fblangref30-ddl-tbl-alter) |
| **SAP HANA** | ✅ | ✅ | ✅ | Full support in HANA 2.0+ | [SAP HANA ALTER TABLE](https://help.sap.com/docs/SAP_HANA_PLATFORM/4fe29514fd584807ac9f2a04f6754767/20d05394751910148a8b990d33efbdc5.html) |
| **Jet (Access)** | ❌ | ❌ | ❌ | No native support | [Access ALTER TABLE](https://docs.microsoft.com/en-us/office/client-developer/access/desktop-database-reference/alter-table-statement-microsoft-access-sql) |
| **MySQL** | ❌ | ❌ | ❌ | No native support | [MySQL ALTER TABLE](https://dev.mysql.com/doc/refman/8.0/en/alter-table.html) |
| **Oracle** | ❌ | ❌ | ❌ | No native support | [Oracle ALTER TABLE](https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/ALTER-TABLE.html) |
| **PostgreSQL** | ✅ | ✅ | ✅ | Full support since PostgreSQL 9.1+ | [PostgreSQL ALTER TABLE](https://www.postgresql.org/docs/current/sql-altertable.html) |
| **Redshift** | ✅ | ✅ | ✅ | Based on PostgreSQL | [Redshift ALTER TABLE](https://docs.aws.amazon.com/redshift/latest/dg/r_ALTER_TABLE.html) |
| **Snowflake** | ✅ | ✅ | ✅ | Full support | [Snowflake ALTER TABLE](https://docs.snowflake.com/en/sql-reference/sql/alter-table) |
| **SQLite** | ✅ | ❌ | ❌ | ADD IF NOT EXISTS since SQLite 3.35.0 | [SQLite ALTER TABLE](https://www.sqlite.org/lang_altertable.html) |
| **SQL Server** | ❌ | ✅ | ✅ | DROP/ALTER IF EXISTS since SQL Server 2016 | [SQL Server ALTER TABLE](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-transact-sql) |

## Sequences

| DBMS | CREATE IF NOT EXISTS | DROP IF EXISTS | ALTER IF EXISTS | Version Notes | Official Documentation |
|------|:-------------------:|:---------------:|:---------------:|---------------|------------------------|
| **DB2** | ✅ | ✅ | ❌ | Support in recent versions | [IBM DB2 CREATE SEQUENCE](https://www.ibm.com/docs/en/db2/11.5?topic=statements-create-sequence) |
| **Firebird** | ❌ | ❌ | ❌ | No native support | [Firebird Generators/Sequences](https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref30/firebird-30-language-reference.html#fblangref30-ddl-sequence) |
| **SAP HANA** | ✅ | ✅ | ✅ | Full support in HANA 2.0+ | [SAP HANA CREATE SEQUENCE](https://help.sap.com/docs/SAP_HANA_PLATFORM/4fe29514fd584807ac9f2a04f6754767/20d5832a75191014909fe3105a2e9bd8.html) |
| **Jet (Access)** | N/A | N/A | N/A | No sequences | [Access AutoNumber](https://docs.microsoft.com/en-us/office/client-developer/access/desktop-database-reference/autonumber-data-type) |
| **MySQL** | N/A | N/A | N/A | No sequences | [MySQL AUTO_INCREMENT](https://dev.mysql.com/doc/refman/8.0/en/example-auto-increment.html) |
| **Oracle** | ❌ | ❌ | ❌ | No native support | [Oracle CREATE SEQUENCE](https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/CREATE-SEQUENCE.html) |
| **PostgreSQL** | ✅ | ✅ | ✅ | Full support since PostgreSQL 9.1+ | [PostgreSQL CREATE SEQUENCE](https://www.postgresql.org/docs/current/sql-createsequence.html) |
| **Redshift** | N/A | N/A | N/A | No sequences | [Redshift IDENTITY](https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_TABLE_NEW.html#r_CREATE_TABLE_NEW-identity) |
| **Snowflake** | ✅ | ✅ | ✅ | Full support | [Snowflake CREATE SEQUENCE](https://docs.snowflake.com/en/sql-reference/sql/create-sequence) |
| **SQLite** | N/A | N/A | N/A | No sequences | [SQLite AUTOINCREMENT](https://www.sqlite.org/autoinc.html) |
| **SQL Server** | ❌ | ✅ | ❌ | DROP IF EXISTS since SQL Server 2016 | [SQL Server CREATE SEQUENCE](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-sequence-transact-sql) |

## Indexes

| DBMS | CREATE IF NOT EXISTS | DROP IF EXISTS | ALTER IF EXISTS | Version Notes | Official Documentation |
|------|:-------------------:|:---------------:|:---------------:|---------------|------------------------|
| **DB2** | ✅ | ❌ | ❌ | CREATE IF NOT EXISTS support | [IBM DB2 CREATE INDEX](https://www.ibm.com/docs/en/db2/11.5?topic=statements-create-index) |
| **Firebird** | ❌ | ❌ | ❌ | No native support | [Firebird CREATE INDEX](https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref30/firebird-30-language-reference.html#fblangref30-ddl-idx-create) |
| **SAP HANA** | ✅ | ✅ | ✅ | Full support in HANA 2.0+ | [SAP HANA CREATE INDEX](https://help.sap.com/docs/SAP_HANA_PLATFORM/4fe29514fd584807ac9f2a04f6754767/20d5832a75191014909fe3105a2e9bd8.html) |
| **Jet (Access)** | ❌ | ❌ | ❌ | Limited support | [Access CREATE INDEX](https://docs.microsoft.com/en-us/office/client-developer/access/desktop-database-reference/create-index-statement-microsoft-access-sql) |
| **MySQL** | ✅ | ✅ | ❌ | Support since MySQL 5.7 | [MySQL CREATE INDEX](https://dev.mysql.com/doc/refman/8.0/en/create-index.html) |
| **Oracle** | ❌ | ❌ | ❌ | No native support | [Oracle CREATE INDEX](https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/CREATE-INDEX.html) |
| **PostgreSQL** | ✅ | ✅ | ❌ | Full support since PostgreSQL 9.1+ | [PostgreSQL CREATE INDEX](https://www.postgresql.org/docs/current/sql-createindex.html) |
| **Redshift** | ✅ | ✅ | ❌ | Based on PostgreSQL | [Redshift Indexes](https://docs.aws.amazon.com/redshift/latest/dg/t_creating_tables.html) |
| **Snowflake** | ✅ | ✅ | ✅ | Full support | [Snowflake Indexes](https://docs.snowflake.com/en/user-guide/tables-clustering-keys) |
| **SQLite** | ✅ | ✅ | ❌ | Support since early versions | [SQLite CREATE INDEX](https://www.sqlite.org/lang_createindex.html) |
| **SQL Server** | ❌ | ✅ | ❌ | DROP IF EXISTS since SQL Server 2016 | [SQL Server CREATE INDEX](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-index-transact-sql) |

## Constraints

| DBMS | ADD IF NOT EXISTS | DROP IF EXISTS | ALTER IF EXISTS | Version Notes | Official Documentation |
|------|:----------------:|:---------------:|:---------------:|---------------|------------------------|
| **DB2** | ❌ | ❌ | ❌ | Limited support | [IBM DB2 Constraints](https://www.ibm.com/docs/en/db2/11.5?topic=statements-alter-table) |
| **Firebird** | ❌ | ❌ | ❌ | No native support | [Firebird Constraints](https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref30/firebird-30-language-reference.html#fblangref30-ddl-tbl-constr) |
| **SAP HANA** | ✅ | ✅ | ✅ | Full support in HANA 2.0+ | [SAP HANA Table Constraints](https://help.sap.com/docs/SAP_HANA_PLATFORM/4fe29514fd584807ac9f2a04f6754767/20d05394751910148a8b990d33efbdc5.html) |
| **Jet (Access)** | ❌ | ❌ | ❌ | No native support | [Access Constraints](https://docs.microsoft.com/en-us/office/client-developer/access/desktop-database-reference/constraint-clause-microsoft-access-sql) |
| **MySQL** | ❌ | ❌ | ❌ | Limited support | [MySQL Constraints](https://dev.mysql.com/doc/refman/8.0/en/create-table-check-constraints.html) |
| **Oracle** | ❌ | ❌ | ❌ | No native support | [Oracle Constraints](https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/constraint.html) |
| **PostgreSQL** | ✅ | ✅ | ✅ | Full support since PostgreSQL 9.1+ | [PostgreSQL Table Constraints](https://www.postgresql.org/docs/current/ddl-constraints.html) |
| **Redshift** | ✅ | ✅ | ✅ | Based on PostgreSQL | [Redshift Table Constraints](https://docs.aws.amazon.com/redshift/latest/dg/t_Defining_constraints.html) |
| **Snowflake** | ✅ | ✅ | ✅ | Full support | [Snowflake Constraints](https://docs.snowflake.com/en/sql-reference/constraints-overview) |
| **SQLite** | ❌ | ❌ | ❌ | Limited constraint support | [SQLite Constraints](https://www.sqlite.org/lang_createtable.html#constraints) |
| **SQL Server** | ❌ | ✅ | ❌ | DROP IF EXISTS since SQL Server 2016 | [SQL Server Constraints](https://docs.microsoft.com/en-us/sql/relational-databases/tables/create-check-constraints) |

### Legend
- ✅ = Supported natively
- ❌ = Not supported or requires workarounds  
- N/A = Feature not available in DBMS

### Key Observations
- **PostgreSQL** and **Snowflake** have the most comprehensive support across all object types
- **SQL Server 2016+** introduced DROP IF EXISTS but still lacks CREATE IF NOT EXISTS for most objects
- **SAP HANA 2.0+** offers full modern SQL conditional support
- **Oracle** and **Firebird** require PL/SQL or custom procedures for similar functionality
- **SQLite 3.35.0** added column ADD IF NOT EXISTS support
- **MySQL** supports schemas (databases) with IF NOT EXISTS since version 5.0
- **Jet/Access** and **SQLite** don't have schema concepts

**Comment by jzabroski** [comment]
What prompt(s) did you use?

**Comment by PhenX** [comment]
> What prompt(s) did you use?

"Give me a table telling me the SQL support for "IF EXISTS" and "IF NOT EXISTS" in create/alter/drop schema, table, column, sequence, index, constraint for these DBMS : db2, firebird, hana, jet, mysql, oracle, postgresql, redshift, snowflake, sqlite and sql server. If support came after a specific version, add a not about it"

and

"can you flip columns and rows, and split create/alter/drop for each object type ? also, add the version note in the cells if needed"
