### ISSUE TITLE
PostgreSQL: Unsupported DbType 'DateTimeOffset'

### ISSUE THREAD

**Issue by ikusmart** [fluentmigrator/fluentmigrator#1304]
I'm using PostgreSQL 12.2 with FluentMigrator 3.2.7. 
I have the following column definition in my migration:

`.WithColumn("createDate").AsDateTimeOffset(7).NotNullable()`

When i run migration, I get the following exception:
```
Rolling back transaction
Unhandled exception: System.NotSupportedException: Unsupported DbType 'DateTimeOffset'
   at FluentMigrator.Runner.Generators.Base.TypeMapBase.GetTypeMap(DbType type, Nullable`1 size, Nullable`1 precision)
   at FluentMigrator.Runner.Generators.Base.ColumnBase.GetTypeMap(DbType value, Nullable`1 size, Nullable`1 precision)
   at FluentMigrator.Runner.Generators.Base.ColumnBase.FormatType(ColumnDefinition column)
   at FluentMigrator.Runner.Generators.Postgres.PostgresColumn.FormatType(ColumnDefinition column)
   at FluentMigrator.Runner.Generators.Base.ColumnBase.Generate(ColumnDefinition column)
   at FluentMigrator.Runner.Generators.Base.ColumnBase.<Generate>b__24_1(ColumnDefinition x)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FluentMigrator.Runner.Generators.Base.ColumnBase.Generate(IEnumerable`1 columns, String tableName)
   at FluentMigrator.Runner.Generators.Postgres.PostgresGenerator.Generate(CreateTableExpression expression)
   at FluentMigrator.Runner.Processors.ProcessorBase.Process(CreateTableExpression expression)
   at FluentMigrator.Expressions.CreateTableExpression.ExecuteWith(IMigrationProcessor processor)
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass80_0.<ExecuteExpressions>b__1()
   at FluentMigrator.Runner.StopWatch.Time(Action action)
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)
   at FluentMigrator.Runner.MigrationRunner.ExecuteMigration(IMigration migration, Action`2 getExpressions)
   at FluentMigrator.Runner.MigrationRunner.ApplyMigrationUp(IMigrationInfo migrationInfo, Boolean useTransaction)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Int64 targetVersion, Boolean useAutomaticTransactionManagement)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Boolean useAutomaticTransactionManagement)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp()
```

If I use folowing code - the migration runs successfully:
`.WithColumn("createDate").AsDateTimeOffset().NotNullable()`

**Comment by jzabroski** [comment]
@ikusmart The Postgres [Date/Time types](https://www.postgresql.org/docs/12/datatype-datetime.html) documentation says the allowed range is 0 to 6.  Quote (**emphasis mine**):

> `time`, `timestamp`, and `interval` accept an optional precision value _p_ which specifies the number of fractional digits retained in the seconds field. By default, there is no explicit bound on precision. **The allowed range of _p_ is from 0 to 6.**`

What behavior were you expecting / like to see for an invalid Postgres precision?

**Comment by jzabroski** [comment]
Fixed.  Now throws ArgumentOutOfRange exception when you pass in an invalid precision.
