### ISSUE TITLE
ArgumentException on Scheme Column Exists after updating Microsoft.Data.Sqlite

### ISSUE THREAD

**Issue by danielkraut** [fluentmigrator/fluentmigrator#1389]
**Describe the bug**
Using syntax `Schema.Table("table").Column("column).Exists()` inside a Migration to check wheter a column exists works fine with Microsoft.Data.Sqlite backend version up to 2.2.6, but fails with version 3.1.10 (didn't try other 3.x) versions. Stack trace:
```
System.ArgumentException
  HResult=0x80070057
  Message=Type of value has a mismatch with column typeCouldn't store <0> in dflt_value Column. Expected type is Byte[].
  Source=System.Data
  StackTrace:
   at System.Data.DataColumn.set_Item(Int32 record, Object value)
   at System.Data.DataTable.NewRecordFromArray(Object[] value)
   at System.Data.DataRowCollection.Add(Object[] values)
   at FluentMigrator.Runner.Processors.DataReaderExtensions.ReadTable(IDataReader reader) in D:\a\1\s\src\FluentMigrator.Runner.Core\Processors\DataReaderExtensions.cs:line 46
   at FluentMigrator.Runner.Processors.DataReaderExtensions.ReadDataSet(IDataReader reader) in D:\a\1\s\src\FluentMigrator.Runner.Core\Processors\DataReaderExtensions.cs:line 25
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Read(String template, Object[] args) in D:\a\1\s\src\FluentMigrator.Runner.SQLite\Processors\SQLite\SQLiteProcessor.cs:line 286
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ColumnExists(String schemaName, String tableName, String columnName) in D:\a\1\s\src\FluentMigrator.Runner.SQLite\Processors\SQLite\SQLiteProcessor.cs:line 90
   at FluentMigrator.Builders.Schema.Column.SchemaColumnQuery.Exists() in D:\a\1\s\src\FluentMigrator\Builders\Schema\Column\SchemaColumnQuery.cs:line 51
   at AppDbMigrations.AddDirtyFlagColumn.Up() in C:\Users\kraut.BRNO\Projekt-Akela\akela-xamarin\Akela\AppDbMigrations\Migrations\2020052200_AddDirtyFlagColumn.cs:line 15
   at FluentMigrator.MigrationBase.GetUpExpressions(IMigrationContext context) in D:\a\1\s\src\FluentMigrator\MigrationBase.cs:line 81
   at FluentMigrator.Runner.MigrationRunner.<>c.<ApplyMigrationUp>b__69_0(IMigration m, IMigrationContext c) in D:\a\1\s\src\FluentMigrator.Runner\MigrationRunner.cs:line 607
   at FluentMigrator.Runner.MigrationRunner.ExecuteMigration(IMigration migration, Action`2 getExpressions) in D:\a\1\s\src\FluentMigrator.Runner\MigrationRunner.cs:line 826
   at FluentMigrator.Runner.MigrationRunner.ApplyMigrationUp(IMigrationInfo migrationInfo, Boolean useTransaction) in D:\a\1\s\src\FluentMigrator.Runner\MigrationRunner.cs:line 623
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Int64 targetVersion, Boolean useAutomaticTransactionManagement) in D:\a\1\s\src\FluentMigrator.Runner\MigrationRunner.cs:line 445
   at FluentMigrator.Runner.MigrationRunner.MigrateUp() in D:\a\1\s\src\FluentMigrator.Runner\MigrationRunner.cs:line 390
   ...

  This exception was originally thrown at this call stack:
    System.Data.Common.ObjectStorage.Set(int, object)
    System.Data.DataColumn.this[int].set(int, object)

```

**To Reproduce**
I created a small project to demonstrate the issue: [MigrationTypeException.zip](https://github.com/fluentmigrator/fluentmigrator/files/5659164/MigrationTypeException.zip)

**Expected behavior**
Checking if column exists succeeds.

**Information (please complete the following information):**
 - Windows 10 x64
 - .NET Framework 4.7.2 (also tried on .NET Core 3.1)
 - FluentMigrator version 3.1.3 / 3.2.9 (I tried both)
 - "in-process runner"
 - Database Management System - SQLite

**Additional context**
Found a similiar issue on EF Core (Microsoft.Data.Sqlite) repository issues page - https://github.com/dotnet/efcore/issues/23490 . Although it doesn't say what changed between versions 2x - 3x. I am not 100% sure if this is an issue with FluentMigrator or Sqlite library.

**Comment by jzabroski** [comment]
Does it fail with Microsoft.Data.Sqlite 3.1.9.  Seems like a pretty wide range of version changes.  A bit strange this issue was closed 22 hours ago by EF Core team, as it doesn't actually appear to be resolved.  However, Brice's comments are helpful to figure out what is happening.  I will try to take a look at your repro.

**Comment by jzabroski** [comment]
@danielkraut Any chance you tested this to see when this broke?  Would do it myself but trying to triage until we get official .NET 5.0 support out the door.

**Comment by danielkraut** [comment]
I just tested all Microsoft.Data.Sqlite 3.x versions, and it seems that 2.2.6 is the last one which works. It already throws the exception with version 3.0.0 (which means netcore 3.0?).

**Comment by jzabroski** [comment]
Thanks. That helps triage.

**Comment by mattbrailsford** [comment]
This can be closed as was resolved in https://github.com/fluentmigrator/fluentmigrator/pull/1580
