### ISSUE TITLE
Running in docker container. Out-of-process - "No migrations found"

### ISSUE THREAD

**Issue by bratherem** [fluentmigrator/fluentmigrator#1401]
**Describe the question**

"No migrations found" in a compiled docker container project.
Assembling the main docker image from `mcr.microsoft.com/dotnet/runtime-deps` with dotnet Sdk 

Custom sdk docker image
```Dockerfile
ARG REPO=mcr.microsoft.com/dotnet/runtime-deps
FROM $REPO:2.1-alpine3.12

# Disable the invariant mode (set in base image)
RUN apk add --no-cache icu-libs

ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8

# Install .NET Core SDK
ENV DOTNET_SDK_VERSION 2.1.811

RUN wget -O dotnet.tar.gz --no-check-certificate https://dotnetcli.azureedge.net/dotnet/Sdk/$DOTNET_SDK_VERSION/dotnet-sdk-$DOTNET_SDK_VERSION-linux-musl-x64.tar.gz \
    && dotnet_sha512='b808643e955c2e3bfcd713623ddaf69999af43966bafedd1af4124e7faa1cebbfefe891d2e540643754c451018ba52d2afca8c27b6d598ceb01a07040864e807' \
    && echo "$dotnet_sha512  dotnet.tar.gz" | sha512sum -c - \
    && mkdir -p /usr/share/dotnet \
    && tar -C /usr/share/dotnet -xzf dotnet.tar.gz \
    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet \
    && rm -f dotnet.tar.gz

ENV \
    # Enable detection of running in a container
    DOTNET_RUNNING_IN_CONTAINER=true \
    # Enable correct mode for dotnet watch (only mode supported in a container)
    DOTNET_USE_POLLING_FILE_WATCHER=true \ 
    # Skip extraction of XML docs - generally not useful within an image/container - helps performance
    NUGET_XMLDOC_MODE=skip

# Install FluentMigrator.DotNet.Cli 3.2.11
RUN dotnet_fm=3.2.11 \
    && dotnet tool install -g FluentMigrator.DotNet.Cli --version $dotnet_fm \
    && export PATH="$PATH:/root/.dotnet/tools"
```

Create project docker image with custom sdk image
```Dockerfile
#Custom sdk docker image
FROM dotnet/core/sdk:2.1-fm3.2.11

WORKDIR /src
COPY ["Middleware.Data.csproj", "Middleware.Data/"]
RUN dotnet restore "Middleware.Data/Middleware.Data.csproj"
COPY . .

WORKDIR "/src/Middleware.Data"
RUN dotnet build "Middleware.Data.csproj" -c Release -o /app/build --no-restore
RUN dotnet publish "Middleware.Data.csproj" -c Release -o /app/publish 

WORKDIR /app/publish
RUN rm -fR /src /app/build
ENTRYPOINT ["/bin/sh"]
```
I get a good image based on which I launch the container.
Next, command to display migrations
```bash
dotnet fm list migrations -p sqlServer2016 -c "Server=192.168.0.1,1433;Database=Middleware;User Id=MiddlewareUser;Password=MiddlewarePassword;" -a Middleware.Data.dll -n "Middleware.Data.Migrations" --nested 
```
Сommand result
```log
-------------------------------------------------------------------------------
Migrations
-------------------------------------------------------------------------------

Unhandled Exception: FluentMigrator.Runner.Exceptions.MissingMigrationsException: No migrations found
   at FluentMigrator.Runner.DefaultMigrationInformationLoader.FindMigrations(IMigrationSource source, IMigrationRunnerConventions conventions, String namespace, Boolean loadNestedNamespaces, String[] tagsToMatch, Boolean includeUntagged) in D:\a\1\s\src\FluentMigrator.Runner\DefaultMigrationInformationLoader.cs:line 185
   at FluentMigrator.Runner.DefaultMigrationInformationLoader.LoadMigrations() in D:\a\1\s\src\FluentMigrator.Runner\DefaultMigrationInformationLoader.cs:line 126
   at FluentMigrator.Runner.MigrationRunner.ListMigrations() in D:\a\1\s\src\FluentMigrator.Runner\MigrationRunner.cs:line 917
   at FluentMigrator.Runner.Initialization.TaskExecutor.Execute() in D:\a\1\s\src\FluentMigrator.Runner\Initialization\TaskExecutor.cs:line 172
   at FluentMigrator.DotNet.Cli.Commands.BaseCommand.ExecuteMigrations(MigratorOptions options, IConsole console) in D:\a\1\s\src\FluentMigrator.DotNet.Cli\Commands\BaseCommand.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass142_0.<OnExecute>b__0()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](IConsole console, String[] args)
   at FluentMigrator.DotNet.Cli.Program.Main(String[] args) in D:\a\1\s\src\FluentMigrator.DotNet.Cli\Program.cs:line 35
```
Command in the assembly of VS project under Windows, the result:
```log
-------------------------------------------------------------------------------
Migrations
-------------------------------------------------------------------------------
202008181818: Migration202008181818MAA1499
202009171654: Migration202009171654MAA1627
202009181834: Migration202009181834MAA1598
202010051508: Migration202010051508MAA1650
202011051541: Migration202011051541MAA1768
202011061723: Migration202011061723CHP327 (not applied)
202012091725: Migration202012091725MAA1796 (not applied)
Task completed.
```
Downgraded version to 3.2.8 - no changes.
Database availability from container - checked.
TargetFramework in .csproj - netcoreapp2.1.
Versions - checked
```XML
    <PackageReference Include="FluentMigrator" Version="3.2.11" />
    <PackageReference Include="FluentMigrator.Console" Version="3.2.11" />
    <PackageReference Include="FluentMigrator.Runner" Version="3.2.11" />
```
How to fix it ?

**Documentation Pages You've Read So Far**

https://github.com/fluentmigrator/fluentmigrator/issues/1383
https://fluentmigrator.github.io/articles/faq.html
https://github.com/fluentmigrator/fluentmigrator/issues/975

**Expected benefit**

In containers, do migrations within сi/сd, and then delete the image and container.

**Information:**

 - OS: alpine-3.12
 - Platform: .NET Core 2.1
 - FluentMigrator version 3.2.11
 - FluentMigrator runner FluentMigrator.DotNet.Cli
 - Database Management System SQLServer or Postgres
 - Database Management System Version "SQL Server 2017", "Postgres12"

**Comment by fubar-coder** [comment]
Did you try specifying the whole path? (`/app/publish/Middleware.Data.dll`)
IMHO it should not be necessary, but maybe it is nonetheless?

**Comment by bratherem** [comment]
> Did you try specifying the whole path? (`/app/publish/Middleware.Data.dll`)
> IMHO it should not be necessary, but maybe it is nonetheless?
> 
> EDIT: Another problem might be that the runner cannot resolve a windows-only assembly, which would cause this problem too.

I indicate explicitly `/app/publish/Middleware.Data.dll` - not successful (

**Comment by bratherem** [comment]
> EDIT: Another problem might be that the runner cannot resolve a windows-only assembly, which would cause this problem too.

Do you want to say that FluentMigrator will not work under Linux?

**Comment by bratherem** [comment]
The problem was `Dockerfile`
Since the project had 
```xml
<CopyLocalLockFileAssemblies> true </CopyLocalLockFileAssemblies>
```
There was no need for the code below
```Dockerfile
...
COPY ["Middleware.Data.csproj", "Middleware.Data/"]
RUN dotnet restore "Middleware.Data/Middleware.Data.csproj"
COPY . .

WORKDIR "/src/Middleware.Data"
RUN dotnet build "Middleware.Data.csproj" -c Release -o /app/build --no-restore
RUN dotnet publish "Middleware.Data.csproj" -c Release -o /app/publish 
...
```
was going to empty dll
Replaced with
```Dockerfile
...
COPY . .
RUN dotnet build "Middleware.Data.csproj" -c Release -o /app/publish
...
```
and everything worked as it should.

Maybe someone will find the case useful.

**Comment by jzabroski** [comment]
@bratherem Thanks.  One other point with your Dockerfile:

> ```dockerfile
> ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false \
>     LC_ALL=en_US.UTF-8 \
>     LANG=en_US.UTF-8
> ```

If you're using Alpine Linux, why are you setting `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` to false?  Maybe you know what you're doing, but I thought that Alpine doesn't ship with globalization data by default, and the Microsoft .NET Docker images for Alpine Linux explicitly set this to true to prevent you from shooting yourself in the foot.  You only set it to `0` if you're going to use apt-get to install the language codecs your app needs.

**Comment by bratherem** [comment]
@jzabroski Thanks, I'll take note!

**Comment by bratherem** [comment]
@jzabroski Without `ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT = false`
falls with an error
```log
!!! Internal connection fatal error.
-------------------------------------------------------------------------------
VersionMigration migrating
-------------------------------------------------------------------------------

Unhandled Exception: System.InvalidOperationException: Internal connection fatal error.
```
