### ISSUE TITLE
How to determine exactly what migration that fails during migration?

### ISSUE THREAD

**Issue by torbjorn-hansson-stratsys** [fluentmigrator/fluentmigrator#1419]
**Describe the question**

I'm calling `IMigrationRunner.MigrateUp()` and a migration that uses `Execute.Sql(string)` fails during execution because it has invalid sql (not important atm). The exception returned is:

```
System.Exception: System.Exception: An error occured executing the following sql:

                CREATE NONCLUSTERED INDEX [IX_SomeIndex] ON [dbo].[SomeTable]
                (
	                [someField] ASC
                ) WHERE (someOtherField <> (1))
            
The error was The operation failed because an index or statistics with name 'IX_SomeIndex' already exists on table 'dbo.SomeTable'.
 ---> System.Data.SqlClient.SqlException: The operation failed because an index or statistics with name 'IX_SomeIndex' already exists on table 'dbo.SomeTable'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at FluentMigrator.Runner.Processors.SqlServer.SqlServerProcessor.ExecuteNonQuery(String sql) in d:\a\1\s\src\FluentMigrator.Runner.SqlServer\Processors\SqlServer\SqlServerProcessor.cs:line 258
   --- End of inner exception stack trace ---
   at FluentMigrator.Runner.Processors.SqlServer.SqlServerProcessor.ExecuteNonQuery(String sql) in d:\a\1\s\src\FluentMigrator.Runner.SqlServer\Processors\SqlServer\SqlServerProcessor.cs:line 268
   at FluentMigrator.Runner.Processors.SqlServer.SqlServerProcessor.Process(String sql) in d:\a\1\s\src\FluentMigrator.Runner.SqlServer\Processors\SqlServer\SqlServerProcessor.cs:line 235
   at FluentMigrator.Runner.Processors.SqlServer.SqlServerProcessor.Execute(String template, Object[] args) in d:\a\1\s\src\FluentMigrator.Runner.SqlServer\Processors\SqlServer\SqlServerProcessor.cs:line 188
   at FluentMigrator.Runner.Processors.ProcessorBase.Execute(String sql) in d:\a\1\s\src\FluentMigrator.Runner.Core\Processors\ProcessorBase.cs:line 261
   at FluentMigrator.Expressions.ExecuteSqlStatementExpression.ExecuteWith(IMigrationProcessor processor) in d:\a\1\s\src\FluentMigrator.Abstractions\Expressions\ExecuteSqlStatementExpression.cs:line 39
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass80_0.<ExecuteExpressions>b__1() in d:\a\1\s\src\FluentMigrator.Runner\MigrationRunner.cs:line 862
   at FluentMigrator.Runner.StopWatch.Time(Action action) in d:\a\1\s\src\FluentMigrator.Runner\StopWatch.cs:line 49
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions) in d:\a\1\s\src\FluentMigrator.Runner\MigrationRunner.cs:line 875
   at FluentMigrator.Runner.MigrationRunner.ExecuteMigration(IMigration migration, Action`2 getExpressions) in d:\a\1\s\src\FluentMigrator.Runner\MigrationRunner.cs:line 832
   at FluentMigrator.Runner.MigrationRunner.ApplyMigrationUp(IMigrationInfo migrationInfo, Boolean useTransaction) in d:\a\1\s\src\FluentMigrator.Runner\MigrationRunner.cs:line 623
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Int64 targetVersion, Boolean useAutomaticTransactionManagement) in d:\a\1\s\src\FluentMigrator.Runner\MigrationRunner.cs:line 445
   at FluentMigrator.Runner.MigrationRunner.MigrateUp() in d:\a\1\s\src\FluentMigrator.Runner\MigrationRunner.cs:line 390
...
```

How can I get the name and/or version of the migration?

**Expected benefit**
Would be much easier to find exactly what migration that fails of instead of searching migrations for a specific string.

**Information (please complete the following information):**
 - OS: Windows 10 Pro
 - Platform .NET Framework 4.7.2
 - FluentMigrator version 3.2.6
 - FluentMigrator.Runner.3.2.6
 - Database Management System SQLServer
 - Database Management System Version SQL Server 2017 Enterprise Edition

**Comment by jzabroski** [comment]
@torbjorn-hansson-stratsys 

I don't run into this problem... usually the output looks something like this (**emphasis mine** to indicate the prelude to running a specific migration):

-------------------------------------------------------------------------------
**2021021610: Issue8193_AlterTableFooAddColumns_Quantity_Price migrating**
-------------------------------------------------------------------------------
Beginning Transaction
AlterTable Foo
CreateColumn Foo Quantity Decimal
!!! An error occured executing the following sql:
ALTER TABLE [OMS].[Foo] ADD [Quantity] DECIMAL(28,10) NOT NULL
The error was ALTER TABLE only allows columns to be added that can contain nulls, or have a DEFAULT definition specified, or the column being added is an identity or timestamp column, or alternatively if none of the previous conditions are satisfied the table must be empty to allow addition of this column. Column 'Quantity' cannot be added to non-empty table 'Foo' because it does not satisfy these conditions.

!!! +- ALTER TABLE only allows columns to be added that can contain nulls, or have a DEFAULT definition specified, or the column being added is an identity or timestamp column, or alternatively if none of the previous conditions are satisfied the table must be empty to allow addition of this column. Column 'Quantity' cannot be added to non-empty table 'Foo' because it does not satisfy these conditions.
Rolling back transaction

**Comment by jzabroski** [comment]
Are you using your own runner?  I dont have this problem with FluentMigrator.Dotnet.Cli or with FluentMigrator.MSBuild.dll
