### ISSUE TITLE
FluentMigrator Async Insert - Cannot access a disposed object. ObjectDisposed_ObjectName_Name

### ISSUE THREAD

**Issue by dogaanismail** [fluentmigrator/fluentmigrator#1444]
**Describe the question**

Hello,

I would like to ask a question that is about async inserting data.

I have been working on my own project that I have been using .Net Core 3.1 and Linq2b ORM tool for. I have a problem that is about inserting data by using async method. I want to insert a log data. There is a method that is called InsertWithInt32IdentityAsync in Linq2Db. This method returns an error that is called **Cannot access a disposed object.Object name: IServiceProvider.**

Here is the implementations.

    ` [HttpPost("createpost")]
      [Authorize]
      public virtual async Task<JsonResult> CreatePost([FromForm] PostCreateApi model)
      {
        var serviceResponse = _postService.Create(model);

        if (serviceResponse.Warnings.Count > 0 || serviceResponse.Warnings.Any())
            return BadResponse(new ResultModel
            {
                Status = false,
                Message = serviceResponse.Warnings.First()
            });
        
        //Here returns an error
        await _logService.InsertLogAsync(Domain.Enumerations.LogLevel.Information, $"PostsController- Create Post Request", 
        JsonConvert.SerializeObject(model));

        return OkResponse(new PostListDto
        {
            Id = serviceResponse.Data.Id,
            Text = serviceResponse.Data?.Text,
            ImageUrl = serviceResponse.Data.ImageUrl?.ToString(),
            CreatedByUserName = serviceResponse.Data?.CreatedByUserName,
            CreatedByUserPhoto = serviceResponse.Data?.CreatedByUserPhoto,
            CreatedDate = serviceResponse.Data.CreatedDate,
            VideoUrl = serviceResponse.Data?.VideoUrl,
            PostType = serviceResponse.Data?.PostType,
            Comments = null
        });
    }`

Here is **InsertLogAsync** method.

    `public virtual async Task<Log> InsertLogAsync(LogLevel logLevel, string shortMessage, string fullMessage = "", AppUser appUser = null)
    {
        var log = new Log
        {
            LogLevel = logLevel,
            ShortMessage = shortMessage,
            FullMessage = fullMessage,
            IpAddress = _webHelper.GetCurrentIpAddress(),
            CustomerId = appUser?.Id,
            PageUrl = _webHelper.GetThisPageUrl(true),
            ReferrerUrl = _webHelper.GetUrlReferrer(),
            CreatedDate = DateTime.UtcNow
        };

        await _logRepository.InsertAsync(log);

        return log;
    }`

Here is **BaseDataProvider InsertEntityAsync** method.

    ` public virtual async Task<TEntity> InsertEntityAsync<TEntity>(TEntity entity) where TEntity : 
      BaseEntity
    {
        using var dataContext = CreateDataConnection();
        entity.Id = await dataContext.InsertWithInt32IdentityAsync(entity);
        return entity;
    }`

Here is **FluentMigratorMetadataReader** class.

    `     #region Fields

        private readonly IMigrationManager _migrationManager;

        #endregion

        #region Ctor

        public FluentMigratorMetadataReader()
        {
            _migrationManager = EngineContext.Current.Resolve<IMigrationManager>();
        }

        #endregion

        #region Utils

        protected T GetAttribute<T>(Type type, MemberInfo memberInfo) where T : Attribute
        {
            var attribute = Types.GetOrAdd((type, memberInfo), t =>
            {
                var tableExpr = Expressions.GetOrAdd(type, entityType => _migrationManager.GetCreateTableExpression(entityType));

                if (typeof(T) == typeof(TableAttribute))
                    return new TableAttribute(tableExpr.TableName) { Schema = tableExpr.SchemaName };

                if (typeof(T) != typeof(ColumnAttribute))
                    return null;

                var column = tableExpr.Columns.SingleOrDefault(cd => cd.Name.Equals(NameCompatibilityManager.GetColumnName(type, memberInfo.Name), StringComparison.OrdinalIgnoreCase));

                if (column is null)
                    return null;

                var columnSystemType = (memberInfo as PropertyInfo)?.PropertyType ?? typeof(string);

                return new ColumnAttribute
                {
                    Name = column.Name,
                    IsPrimaryKey = column.IsPrimaryKey,
                    IsColumn = true,
                    CanBeNull = column.IsNullable ?? false,
                    Length = column.Size ?? 0,
                    Precision = column.Precision ?? 0,
                    IsIdentity = column.IsIdentity,
                    DataType = SqlDataType.GetDataType(columnSystemType).Type.DataType
                };
            });

            return (T)attribute;
        }`

Here is some **screenshots** I have taken. 

[https://i.stack.imgur.com/Y8tAC.png](https://i.stack.imgur.com/Y8tAC.png)
[https://i.stack.imgur.com/Q90to.png](https://i.stack.imgur.com/Q90to.png)
[https://i.stack.imgur.com/vFLTn.png](https://i.stack.imgur.com/vFLTn.png)
[https://i.stack.imgur.com/CJSgE.png](https://i.stack.imgur.com/CJSgE.png)

Here is the **Stack Trace.**

at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType) 
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider) 
at FluentMigrator.Infrastructure.MigrationContext..ctor(IQuerySchema querySchema, IServiceProvider serviceProvider, Object context, String connection) 
at DevPlatform.Data.Migrations.MigrationManager.CreateNullMigrationContext() in C:\Projects\DevPlatform\DevPlatform.Data\Migrations\MigrationManager.cs:line 165 
at DevPlatform.Data.Migrations.MigrationManager.GetCreateTableExpression(Type type) in C:\Projects\DevPlatform\DevPlatform.Data\Migrations\MigrationManager.cs:line 240 
at DevPlatform.Data.Mapping.FluentMigratorMetadataReader.<>c__DisplayClass2_01.<GetAttribute>b__1(Type entityType) in C:\Projects\DevPlatform\DevPlatform.Data\Mapping\FluentMigratorMetadataReader.cs:line 42 
at System.Collections.Concurrent.ConcurrentDictionary2.GetOrAdd(TKey key, Func2 valueFactory) at DevPlatform.Data.Mapping.FluentMigratorMetadataReader.<>c__DisplayClass2_01.b__0(ValueTuple2 t) in C:\Projects\DevPlatform\DevPlatform.Data\Mapping\FluentMigratorMetadataReader.cs:line 42 
at System.Collections.Concurrent.ConcurrentDictionary2.GetOrAdd(TKey key, Func2 valueFactory) 
at DevPlatform.Data.Mapping.FluentMigratorMetadataReader.GetAttribute[T](Type type, MemberInfo memberInfo) in C:\Projects\DevPlatform\DevPlatform.Data\Mapping\FluentMigratorMetadataReader.cs:line 40 
at DevPlatform.Data.Mapping.FluentMigratorMetadataReader.GetAttributes[T](Type type, Type attributeType, MemberInfo memberInfo) in C:\Projects\DevPlatform\DevPlatform.Data\Mapping\FluentMigratorMetadataReader.cs:line 76 
at DevPlatform.Data.Mapping.FluentMigratorMetadataReader.GetAttributes[T](Type type, Boolean inherit) in C:\Projects\DevPlatform\DevPlatform.Data\Mapping\FluentMigratorMetadataReader.cs:line 97 
at LinqToDB.Mapping.MappingSchema.<>c__DisplayClass51_01.b__0(IMetadataReader mr) 
at System.Linq.Enumerable.d__1813.MoveNext() 
at System.Collections.Generic.LargeArrayBuilder1.AddRange(IEnumerable1 items) 
at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable1 source) 
at LinqToDB.Mapping.MappingSchema.GetAttributes[T](Type type, Boolean inherit) 
at LinqToDB.Mapping.MappingSchema.GetAttributes[T](Type type, Func2 configGetter, Boolean inherit, Boolean exactForConfiguration) 
at LinqToDB.Mapping.MappingSchema.GetAttribute[T](Type type, Func2 configGetter, Boolean inherit) 
at LinqToDB.Mapping.EntityDescriptor.Init() 
at LinqToDB.Mapping.EntityDescriptor..ctor(MappingSchema mappingSchema, Type type) 
at LinqToDB.Mapping.MappingSchema.<>c.b__92_0(ICacheEntry o, <>f__AnonymousType1312 key, MappingSchema context) 
at LinqToDB.Common.Internal.Cache.CacheExtensions.GetOrCreate[TItem,TKey,TContext](IMemoryCache cache, TKey key, TContext context, Func4 factory) 
at LinqToDB.Mapping.MappingSchema.GetEntityDescriptor(Type type) 
at LinqToDB.Linq.QueryRunner.GetType[T](T obj, IDataContext db) 
at LinqToDB.Linq.QueryRunner.InsertWithIdentity`1.d__2.MoveNext()

**Github Repository**

You can look at my own project that is called DevPlatform. I am working on a async logging mechanism for the project.

Here is the Github repository link.

https://github.com/dogaanismail/DevPlatform/tree/DevPlatform/Feature/Task-25-logging-mechanism-must-be-implemented

Information (please complete the following information):

OS: Windows 10 Pro
Platform .NET 5
FluentMigrator version 3.2.15
FluentMigrator runner FluentMigrator.DotNet.Cli
Database Management System SQLServer
Database Management System Version SQL Server 2019 Standard Edition

**Additional context**
I have asked this question on StackOverFlow. You can see below.
[https://stackoverflow.com/questions/66845518/linq2db-async-insert-cannot-access-a-disposed-object-objectdisposed-objectnam](https://stackoverflow.com/questions/66845518/linq2db-async-insert-cannot-access-a-disposed-object-objectdisposed-objectnam)

In addition, I have submitted a new issue for Linq2Db. You can see below.
[https://github.com/linq2db/linq2db/issues/2917](https://github.com/linq2db/linq2db/issues/2917)

**Comment by dogaanismail** [comment]
The problem has been solved by editing **CreateTableExpressionBuilder** and calling _migrationContext instead of calling CreateNullMigrationContext function.

Instead of the following code block;

       ` public virtual CreateTableExpression GetCreateTableExpression(Type type)
        {
            var expression = new CreateTableExpression { TableName = NameCompatibilityManager.GetTableName(type) };
            var builder = new CreateTableExpressionBuilder(expression, CreateNullMigrationContext());

            RetrieveTableExpressions(type, builder);

            return builder.Expression;
        }`

I have changed **CreateTableExpressionBuilder** for this problem.

     `public virtual CreateTableExpression GetCreateTableExpression(Type type)
        {
            var expression = new CreateTableExpression { TableName = NameCompatibilityManager.GetTableName(type) };
            var builder = new CreateTableExpressionBuilder(expression, _migrationContext);

            RetrieveTableExpressions(type, builder);

            return builder.Expression;
        }`


**CreateNullMigrationContext** function returns an error as I have mentioned about it.


Thank you very much. @MaceWindu.
We can close the issue.
