### ISSUE TITLE
FormatException with creating column with default json value ("{}")

### ISSUE THREAD

**Issue by kroliczek94** [fluentmigrator/fluentmigrator#1457]
Hello, I have a problem with FluentMigrator after update to from `3.1.3` to `3.2.15`.

**Describe the bug**
I am updating my environment from to .NET 5, so also I am updating all libraries in system. Earlier, I had some column with containing Json data. For default it should be empty Json Object - {}. As can I see StringBuilder.AppendFormat recognize this empty object braces as format tokens (without number inside).

**To Reproduce**
Following statement lead me to bug:

`Alter.Table("campaign_records").InSchema("campaigns").AddColumn("record_data").AsCustom("jsonb").WithDefaultValue("{}");`

**Expected behavior**
It should execute migration without error.

**Information (please complete the following information):**
 - OS: Windows 10
 - Platform .NET 5
 - FluentMigrator version 3.2.15
 - FluentMigrator runner FluentMigrator.Runner, 3.2.15
 - Database Management System: Postgres
 - Database Management System Version: 10

**Comment by jzabroski** [comment]
What error do you get? Thanks

**Comment by fubar-coder** [comment]
@jzabroski To clarify, I guess that you asked for the stack trace, to get to the location where the `{}` aren't escaped correctly?

**Comment by jzabroski** [comment]
Yes, a stack trace eith full exceptions message is helpful. Ex.ToString()

**Comment by kroliczek94** [comment]
Hi guys, thanks for you answer:

`2021-04-22 14:11:04:740 [ERROR] Gillie.DbUpdater.Program - Error occured on migrate application
System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.Text.StringBuilder.AppendFormat(String format, Object[] args)
   at FluentMigrator.Runner.Generators.Postgres.PostgresGenerator.Generate(CreateColumnExpression expression)
   at FluentMigrator.Runner.Processors.ProcessorBase.Process(CreateColumnExpression expression)
   at FluentMigrator.Expressions.CreateColumnExpression.ExecuteWith(IMigrationProcessor processor)
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass80_0.<ExecuteExpressions>b__1()
   at FluentMigrator.Runner.StopWatch.Time(Action action)
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)
   at FluentMigrator.Runner.MigrationRunner.ExecuteMigration(IMigration migration, Action`2 getExpressions)
   at FluentMigrator.Runner.MigrationRunner.ApplyMigrationUp(IMigrationInfo migrationInfo, Boolean useTransaction)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Int64 targetVersion, Boolean useAutomaticTransactionManagement)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Boolean useAutomaticTransactionManagement)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp()`

**Comment by jzabroski** [comment]
Simple workaround for now is to use {{}} to escape string format

**Comment by fubar-coder** [comment]
Other dialects might be affected too.
