### ISSUE TITLE
migration with execute sql with multiple commit-statements and multipleActiveResultSets set to true throws mars error on .net core

### ISSUE THREAD

**Issue by guppylein** [fluentmigrator/fluentmigrator#1589]
**Describe the bug**
I'm just moving from a Full .NET-project to .netcore. Running a migration with connection string _MultipleActiveResultSets=true_ with the following Sql throws MARS-error.
I updated from FluentMigrator 1.6.2 to 3.1.3. Running the same migration in Full .NET framework and Version 1.6.2 does not throw an error.

```
public override void Up()
{
    Execute.Sql(@"
        /* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
        BEGIN TRANSACTION
        SET QUOTED_IDENTIFIER ON
        SET ARITHABORT ON
        SET NUMERIC_ROUNDABORT OFF
        SET CONCAT_NULL_YIELDS_NULL ON
        SET ANSI_NULLS ON
        SET ANSI_PADDING ON
        SET ANSI_WARNINGS ON
        COMMIT
        BEGIN TRANSACTION
        GO
        EXECUTE sp_rename N'dbo.table1.name', N'Tmp_Name', 'COLUMN' 
        GO
        COMMIT
    ");
}
```

**Exception**
```
System.Exception: An error occured executing the following sql:
BEGIN TRANSACTION
                SET QUOTED_IDENTIFIER ON
                SET ARITHABORT ON
                SET NUMERIC_ROUNDABORT OFF
                SET CONCAT_NULL_YIELDS_NULL ON
                SET ANSI_NULLS ON
                SET ANSI_PADDING ON
                SET ANSI_WARNINGS ON
                COMMIT
                BEGIN TRANSACTION
The error was A transaction that was started in a MARS batch is still active at the end of the batch. The transaction is rolled back.
 ---> System.Data.SqlClient.SqlException: A transaction that was started in a MARS batch is still active at the end of the batch. The transaction is rolled back.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at FluentMigrator.Runner.Processors.SqlServer.SqlServerProcessor.<>c__DisplayClass38_0.<ExecuteBatchNonQuery>b__1(Object sender, SpecialTokenEventArgs args) in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner.SqlServer/Processors/SqlServer/SqlServerProcessor.cs:line 293
   at FluentMigrator.Runner.BatchParser.SqlBatchParser.<>c__DisplayClass10_0.<Process>b__1(Object sender, SpecialTokenEventArgs evt) in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner.Core/BatchParser/SqlBatchParser.cs:line 93
   at FluentMigrator.Runner.BatchParser.SearchStatus.FindTokenOrRangeStart() in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner.Core/BatchParser/SearchStatus.cs:line 202
   at FluentMigrator.Runner.BatchParser.SqlBatchParser.Process(ITextSource source, Boolean stripComments) in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner.Core/BatchParser/SqlBatchParser.cs:line 103
   at FluentMigrator.Runner.Processors.SqlServer.SqlServerProcessor.ExecuteBatchNonQuery(String sql) in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner.SqlServer/Processors/SqlServer/SqlServerProcessor.cs:line 305
   --- End of inner exception stack trace ---
   at FluentMigrator.Runner.Processors.SqlServer.SqlServerProcessor.ExecuteBatchNonQuery(String sql) in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner.SqlServer/Processors/SqlServer/SqlServerProcessor.cs:line 324
   at FluentMigrator.Runner.StopWatch.Time(Action action) in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner/StopWatch.cs:line 51
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions) in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner/MigrationRunner.cs:line 789
   at FluentMigrator.Runner.MigrationRunner.ApplyMigrationUp(IMigrationInfo migrationInfo, Boolean useTransaction) in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner/MigrationRunner.cs:line 534
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Int64 targetVersion, Boolean useAutomaticTransactionManagement) in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner/MigrationRunner.cs:line 365
```

**To Reproduce**
Create a simple table:
```
public override void Up()
{
    Create.Table("table1")
        .WithColumn("Id").AsGuid().NotNullable().PrimaryKey();
        .WithColumn("name").AsString(100);
}
```
Run another migration like shown in description above with _Execute.Sql_ and two _COMMIT_ statements (the above SQL ist auto generated by sql management studio, when renaming a column).
**Important**: The connection string used for migration must have _MultipleActiveResultSets_ set to _true_.

**Expected behavior**
Migration should not throw MARS-error and should get executed without error, as it does
- on Full .NET-Framework 4.8 with MultipleActiveResultSets=true
- on .NET Core 2.x/3.1/5 with MultipleActiveResultSets=false

**Information:**
 - OS: Windows 10
 - Platform .NET Core 2.x , .NET Core 3.x, .NET 5
 - FluentMigrator version 3.1.3
 - FluentMigrator runner
 - Database Management System: SQLServer, SQLLocalDb
 - Database Management System Version: SQL Server 2019 Express/SQL Server 2019 LocalDB

**Additional context**
None

**Comment by jzabroski** [comment]
> I updated from FluentMigrator 1.6.2 to 3.1.3. Running the same migration in Full .NET framework and Version 1.6.2 does not throw an error.

I believe that's because you are using an older version of the .NET SQL Native Client , which allowed some pretty bad T-SQL apparently.  I'm shocked the SQL you pasted even works.  Closing this until you can give me a more robust repro.

However, here is your problem if you can't see it:
```sql
COMMIT
BEGIN TRANSACTION
GO -- YOU HAVE A "GO" RIGHT AFTER A "BEGIN TRANSACTION". THIS DOESNT MAKE ANY SENSE.
```

**Comment by guppylein** [comment]
@jzabroski Thanks for testing, the posted SQL was shortened, but the `COMMIT/BEGIN TRANSACTION`-part is really auto-generated by Microsoft SQL Server Management Studio, if you rename a column in the designer ;)

I'll will have a look at my referenced sql-packages, so maybe the problem lies there.
