### ISSUE TITLE
SQLite FluentMigrator InSchema Error

### ISSUE THREAD

**Issue by msfreed** [fluentmigrator/fluentmigrator#1772]
**Describe the bug**
Creating a table using InSchema is failing with an error message of "unknown database <schema name>".

**To Reproduce**
Create.Table("table_name").InSchema("public")

**Expected behavior**
The table should be created.

**Information (please complete the following information):**
 - OS: Windows 11
 - Platform: .NET 8
 - FluentMigrator version: 5.2.0
 - FluentMigrator runner: in-process
 - Database Management System: SQLite
 - Database Management System Version: Microsoft.EntityFrameworkCore.Sqlite v8.0.3

**Additional context**
This works in FluentMigrator v3.3.2

Stack Trace

 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'unknown database \"public\"'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)
   --- End of inner exception stack trace ---
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Process(String sql)
   at FluentMigrator.Runner.Processors.ProcessorBase.Process(CreateTableExpression expression)
   at FluentMigrator.Expressions.CreateTableExpression.ExecuteWith(IMigrationProcessor processor)
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass81_0.<ExecuteExpressions>b__1()
   at FluentMigrator.Runner.StopWatch.Time(Action action)
   at FluentMigrator.Runner.MigrationRunner.AnnounceTime(String message, Action action)
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)
   at FluentMigrator.Runner.MigrationRunner.ExecuteMigration(IMigration migration, Action`2 getExpressions)
   at FluentMigrator.Runner.MigrationRunner.ApplyMigrationUp(IMigrationInfo migrationInfo, Boolean useTransaction)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Int64 targetVersion, Boolean useAutomaticTransactionManagement)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Boolean useAutomaticTransactionManagement)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp()

**Comment by jzabroski** [comment]
SQLite does not directly support schemas. You have to attach a database to the connection. This is definitely working correctly. What steps did you do to debug this?

**Comment by msfreed** [comment]
Thanks for the response and documentation. You're right that the schema-name ("public") is not "main", "temp", or the name of the database. Any idea why this works in v3.3.2? If this was a breaking change, is there any FluentMigrator documentation that explains an upgrade path?

Here is how the service collection is being setup. 
```
new ServiceCollection()
            .AddFluentMigratorCore()
            .ConfigureRunner(rb => rb.AddSQLite().WithGlobalConnectionString("Data Source=test;Mode=Memory;Cache=Shared").ScanIn(assemblies).For.Migrations())
            .BuildServiceProvider();
```

**Comment by jzabroski** [comment]
I don't know. We don't have regression tests for incorrect usage "working". What did you do to debug this so far?

**Comment by msfreed** [comment]
I haven't debugged past updating to the latest versions of Microsoft.EntityFrameworkCore.Sqlite and FluentMigrator. Using v5.2.0 of FluentMigrator for SQLite does not work with the latest stable version (v8.0.3) of Microsoft.EntityFrameworkCore.Sqlite. Using v3.3.2 of FluentMigrator does work with the latest stable version of Microsoft.EntityFrameworkCore.Sqlite. So it seemed to me that it was a change in FluentMigrator, not the underlying library.

Based on the SQLite documentation you referenced, it sounds like there was probably a breaking change (intentional or not) to the SQLite runner to not support an incompatible SQLite schema-name -- that's fine. I was just trying to understand what the upgrade path from a FluentMigrator perspective was. Sounds like the answer is to use a valid SQLite schema-name.

**Comment by jzabroski** [comment]
I had a reply written but it got lost somehow.

Put simply, in 3.3, Sqlite Generator ignored the schema. In 5.0, it assumes you have attached a second database corresponding to the schema argument in the migration.

To revert to 3.3 behavior, remove the InSchema and With Schema from your code. If you deploy to multiple DB providers, use IfDatabase to handle SQLite and (processorId ) => processorId! = ProcessorId.SQLite

If you query your sqlite_schema table after running the migration against 3.3, the issue will be clear.
