### ISSUE TITLE
Not working with mysqldata 6.10.4

### ISSUE THREAD

**Issue by bonesoul** [fluentmigrator/fluentmigrator#821]
failing in;

https://github.com/fluentmigrator/fluentmigrator/blob/f17dca3ba0ada883bf016d7bf297c9e0b8b8bdf7/src/FluentMigrator.Runner/Processors/DbFactoryBase.cs#L78

null reference exception

**Comment by smartmsdn** [comment]
I got the same exception with this stack trace

`   at FluentMigrator.Runner.Processors.DbFactoryBase.CreateDataAdapter(IDbCommand command) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\Processors\DbFactoryBase.cs:line 77
   at FluentMigrator.Runner.Processors.MySql.MySqlProcessor.Read(String template, Object[] args) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\Processors\MySql\MySqlProcessor.cs:line 135
   at FluentMigrator.Runner.Processors.MySql.MySqlProcessor.ReadTableData(String schemaName, String tableName) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\Processors\MySql\MySqlProcessor.cs:line 128
   at FluentMigrator.Runner.VersionLoader.LoadVersionInfo() in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\VersionLoader.cs:line 188
   at FluentMigrator.Runner.VersionLoader..ctor(IMigrationRunner runner, IAssemblyCollection assemblies, IMigrationConventions conventions) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\VersionLoader.cs:line 50
   at FluentMigrator.Runner.MigrationRunner..ctor(IAssemblyCollection assemblies, IRunnerContext runnerContext, IMigrationProcessor processor) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:line 102
   at FluentMigrator.Runner.MigrationRunner..ctor(Assembly assembly, IRunnerContext runnerContext, IMigrationProcessor processor) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:line 72`

**Comment by smartmsdn** [comment]
Downgrading `MySql.Data` package to 6.9.10 seems to work

**Comment by bonesoul** [comment]
yep exactly so.

**Comment by escarls** [comment]
Oracle have removed the CreateDataAdapter() that FluentMigrator uses in version 6.10.5, it seems.
