### ISSUE TITLE
Profile causes Object null exception

### ISSUE THREAD

**Issue by Hiimdave** [fluentmigrator/fluentmigrator#904]
Using version 3.1.2, if I have even a Profile in my source code (not even setting it to run) causes the `runner.MigrateUp()` to throw a Null exception.

Below is the Program.cs (basic implementation) and the Profile code.  If I comment out the entire class the Migrations in my project work fine, but just having a profile in the codebase is causing issues.

I've tried versions of Program.cs with the `ScanIn()` set to just `.For.Migrations()` as well as the version below with the same result.

Exception Details:
- Message: Object reference not set to an instance of an object.
- StackTrace: at FluentMigrator.Runner.Infrastructure.DefaultMigrationRunnerConventions.GetMigrationInfoForMigrationImpl(IMigration migration) in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner.Core/Infrastructure/DefaultMigrationConventions.cs:line 77
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at FluentMigrator.Runner.DefaultMigrationInformationLoader.LoadMigrations() in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner/DefaultMigrationInformationLoader.cs:line 122
   at FluentMigrator.Runner.MigrationRunner.GetUpMigrationsToApply(Int64 version)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Int64 targetVersion, Boolean useAutomaticTransactionManagement) in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner/MigrationRunner.cs:line 353
   at DatabaseGenerator.Program.UpdateDatabase(IServiceProvider serviceProvider) in C:\Bitbucket\KRCODE\freedom-utilityapps\DBTestDataTool\DatabaseGenerator\Program.cs:line 63
   at DatabaseGenerator.Program.Main(String[] args) in C:\Bitbucket\KRCODE\freedom-utilityapps\DBTestDataTool\DatabaseGenerator\Program.cs:line 28

**Program.cs**
```
using FluentMigrator.Runner;
using FluentMigrator.Runner.Initialization;
using Microsoft.Extensions.DependencyInjection;
using System;

static void Main(string[] args)
{
    var serviceProvider = CreateServices();
    using (var scope = serviceProvider.CreateScope())
    {
        UpdateDatabase(scope.ServiceProvider);
    }
}

private static IServiceProvider CreateServices()
{
    var assembly = typeof(MyMigration).Assembly;
    var connectionString = "redacted";

    return new ServiceCollection()
        .AddFluentMigratorCore()
        .ConfigureRunner(rb => rb
            .AddSqlServer2016()
            .WithGlobalConnectionString(connectionString)                    
            .ScanIn(assembly).For.All())
        .AddLogging(lb => lb.AddFluentMigratorConsole())
        .BuildServiceProvider(validateScopes: false);
}

private static void UpdateDatabase(IServiceProvider serviceProvider)
{
    var runner = serviceProvider.GetRequiredService<IMigrationRunner>();
    runner.MigrateUp();
} 
```

Profile.cs
```
using FluentMigrator;

[Profile("Development")]
public class Development : Migration
{
        public override void Up() { }
        public override void Down() { }
}
```

**Comment by fubar-coder** [comment]
Fix is available in 3.1.3 (released)
